"""SQL, the DuckDB dialect.

`grammar/` is DuckDB's PEG grammar, vendored verbatim and never edited. It is
data rather than source: 40 `.gram` files, 5 keyword lists, two short lists
lifted out of upstream's `grammar_types.yml` and `compiled_grammar.cpp` because
they are decisions the grammar text does not record, the MIT license they come
under, and a `VENDOR` file recording the commit they came from and the SHA-256
of each one. `tools/vendor_grammar.sh` is the only thing allowed to write into
it.

`generated/` is what `tools/gen_grammar.py` makes of that: one flat node array
covering every rule, and one sorted keyword table. It is checked in, so a
contributor with no Python and no network can still build firepanda, and CI
regenerates it and fails on any diff, which is what actually stops somebody hand
editing a table.

`table.mojo` reads the generated tables back into a `Grammar`. `token.mojo` cuts
a query into tokens and `matcher.mojo` walks the rule table over them, so
`parse(sql, grammar)` is a whole query in and a tree of rule indices out.

`ast.mojo` is the shape the rest of the engine binds against, three arenas of
fixed size nodes that hold no grammar rule names, and `printer.mojo` turns one
back into SQL text. `transform.mojo` is what sits between the parse tree and
the AST, and it is the only file that knows a grammar rule name.

`catalog.mojo` is the namespace a query's names are resolved against: session
scoped, no storage, a frame or a view under each name.

`bind.mojo` is where a name written in a query becomes a pair of indices: the
bindings a query level offers, the chain of levels a subquery sits inside, and
the record of what a correlated one reached out for.

`types.mojo` is DuckDB's type set rather than firepanda's, because the two do
not line up: DuckDB has `DECIMAL(p, s)` and `HUGEINT`, and the engine's
`LogicalType` has neither, so a front end that reused it would answer
`1.1 + 2.2` with a binary float where DuckDB gives exactly `3.3`.

`cast.mojo` is the lattice over those types: what `COALESCE`, `CASE` and a
`UNION` branch agree on when a query hands them two different types. Both of
its tables were generated by asking DuckDB, defects included, because a lattice
that was merely correct would bind queries DuckDB refuses.

`arith.mojo` is a different question from the lattice and gives a different
answer: `COALESCE` over a `TINYINT` and a `UTINYINT` is a `SMALLINT`, and
adding the same two is a `BIGINT`. DuckDB binds an operator by picking an
overload rather than by joining a lattice, so this is a second table and not a
view of the first one.

`star.mojo` is what a `*` stands for, and the three modifiers a query can hang
off one. `bind.mojo` already knows the columns and their order, so this is
`EXCLUDE`, `REPLACE` and `RENAME` over that, including the two places DuckDB is
wrong: a `REPLACE` that matches twice loses a column, and a duplicate `RENAME`
entry is blamed on the `EXCLUDE` list.

`classify.mojo` is which calls in an expression are aggregates and which are
windows, which clauses refuse each of them, and whether a reference is covered
by the `GROUP BY` list. The name sets and the wording of every refusal were
read off DuckDB rather than guessed, down to the two different sentences it
uses for one rule broken in the select list and in `HAVING`.

`subquery.mojo` is the four shapes a `SELECT` can be written in inside an
expression: scalar, `EXISTS`, `IN` and a quantified comparison. Each has its
own arity rule, `EXISTS` is the one that never counts columns at all, and
correlation is read off what `bind.mojo` recorded rather than found by walking
the tree afterwards.

`cte.mojo` is what a `WITH` binds and where each name can be said. Entries bind
in order, so naming a later one is a missing table rather than a forward
reference, a column alias list is a prefix and is half applied when it is the
wrong length, and one message covers all three ways a recursive CTE can be
written wrong.

`registry.mojo` is the tier 1 function catalog: what a name is, which overloads
it has, and what the refusal says when there is no such name or no such call.
Every signature in it was read off DuckDB rather than written down from what a
function ought to do, which is why `sum` over a boolean gives back a `HUGEINT`
and `length` accepts a `BIT`.

`casts.mojo` is what an implicit cast costs, which is the other half of what a
name's overloads are for. DuckDB publishes no such table, so
`tools/gen_casts.py` solves one out of the choices DuckDB makes over a couple
of thousand calls and checks it by replaying every one of them.

`resolve.mojo` is the scoring itself: the cheapest candidate wins, an argument
already of the right type is free, and a call with no cheapest candidate is
refused in DuckDB's own words rather than decided.

`plan.mojo` is where the SQL front end stops being its own thing and becomes a
caller of the engine. It lowers a bound `SELECT` into the same
`firepanda.plan.Plan` the dataframe API builds, bottom up in the order the
clauses run in, and the rule it works under is that no plan node may have only a
SQL constructor. A shape SQL can express and the plan cannot is a gap to close
in the plan rather than a private node to add here.

`unsupported.mojo` is the line between what the grammar accepts and what
firepanda runs. Every refusal is an entry in its table rather than a `raise`
written where the cases ran out, which is what lets `sql_support()` list the
whole set. See docs/specs/sql/00-README.md.
"""

from .arith import (
    OP_ADD,
    OP_DIVIDE,
    OP_INT_DIVIDE,
    OP_MODULO,
    OP_MULTIPLY,
    OP_SUBTRACT,
    arithmetic_type,
    negation_type,
    no_such_operator,
    no_such_unary_operator,
)
from .ast import Ast, Expr, Ref, Stmt
from .classify import (
    CLAUSE_GROUP,
    CLAUSE_HAVING,
    CLAUSE_ORDER,
    CLAUSE_QUALIFY,
    CLAUSE_SELECT,
    CLAUSE_WHERE,
    Uses,
    aggregate_names,
    check_clause,
    check_nesting,
    covered,
    inspect,
    is_aggregate,
    needs_over,
    nested_aggregate,
    no_aggregates_here,
    no_windows_here,
    not_grouped,
    not_grouped_in_having,
    qualify_needs_a_window,
    same,
    window_in_aggregate,
    window_in_window,
    window_only_names,
)
from .bind import Binding, Reference, Scope, Scopes
from .cast import cannot_mix, common_type
from .casts import Casts
from .catalog import Catalog, View
from .cte import (
    NOT_A_CTE,
    Cte,
    Ctes,
    aliased,
    anchored,
    check_modifiers,
    circular_reference,
    duplicate_name,
    no_limit,
    no_ordering,
    read_ctes,
    reference_count,
)
from .generated.casts import ANY_COST, NO_CAST
from .generated.functions import (
    DUCKDB_VERSION,
    KIND_AGGREGATE,
    KIND_MACRO,
    KIND_SCALAR,
)
from .matcher import Parse, ParseNode, parse, parse_rule, parse_unfiltered
from .plan import Lowered, lower
from .printer import (
    needs_quoting,
    print_expr,
    print_ref,
    print_stmt,
    quote_name,
    quote_string,
)
from .registry import (
    NO_SLOT,
    ROLE_ANY,
    ROLE_EXACT,
    ROLE_LIST,
    ROLE_TEMPLATE,
    ROLE_UNKNOWN,
    Overload,
    Registry,
)
from .resolve import (
    NO_MATCH,
    TEMPLATE_COST,
    Resolution,
    ambiguity,
    resolve,
    score,
)
from .run import run
from .star import (
    NOT_REPLACED,
    Renaming,
    Replacement,
    Selected,
    Target,
    empty_select_list,
    expand,
)
from .subquery import (
    SHAPE_EXISTS,
    SHAPE_IN,
    SHAPE_NONE,
    SHAPE_QUANTIFIED,
    SHAPE_SCALAR,
    Subquery,
    about,
    cannot_compare,
    check_columns,
    correlated,
    outer_references,
    too_many_rows,
    wrong_column_count,
)
from .table import Grammar, GrammarNode, memoized_rules, overridden_rules
from .token import Token, tokenize, token_text
from .transform import Transform
from .types import (
    SqlType,
    decimal,
    engine_type,
    parse_type,
    type_for,
    type_name,
)
from .unsupported import NO_REFUSAL, Refusal, feature_of, refusal, sql_support
