"""What an arithmetic operator gives back, which is not what the lattice says.

`cast.mojo` answers what two types agree on when a query puts them side by
side. This answers a different question, and the two disagree: the common type
of a `TINYINT` and a `UTINYINT` is a `SMALLINT`, and `1::TINYINT +
1::UTINYINT` is a `BIGINT`. DuckDB binds an operator by picking an overload
rather than by joining a lattice, and there is no overload taking one signed
and one unsigned argument, so a mixed pair widens until it reaches a type that
holds both sides of the operation. Using the lattice here would give the wrong
answer on every mixed comparison a real schema produces.

The table was generated by asking DuckDB 1.5 for `typeof(a + b)` over every
pair, and the same table serves `-`, `*`, `//` and `%`, which was checked
rather than assumed.

`/` is not in it. Division on two integers is floating point in this dialect,
so `1 / 2` is `0.5` and a `DOUBLE`, and `//` is what integer division is
spelled. That is one of the differences most likely to go unnoticed, because
the query still runs and the number is still a number.

A decimal derives its width and scale from the operands rather than taking
them from a table, and each operator derives them differently. Addition needs
one more digit than the wider operand because a carry can happen, so
`DECIMAL(4,2) + DECIMAL(6,3)` is `DECIMAL(7,3)`. Multiplication adds both
widths and both scales, so `DECIMAL(4,2) * DECIMAL(6,3)` is `DECIMAL(10,5)`.
Modulo takes neither and uses the lattice join. Division gives up and returns
a `DOUBLE`. All four saturate at width 38 rather than raising, so
`DECIMAL(38,2) + DECIMAL(38,2)` is `DECIMAL(38,2)` and the carry it asked for
is quietly not there.

There is a second ceiling at width 18, which is the one nobody sees coming.
DuckDB stores a decimal in the narrowest integer that holds it and will not
promote a pair that both fit in sixty four bits into a hundred and twenty
eight bit arithmetic, so `DECIMAL(18,6) + DECIMAL(18,6)` is `DECIMAL(18,6)`
while `DECIMAL(19,6) + DECIMAL(19,6)` is `DECIMAL(20,6)`. Narrowing, not
widening, is what the wider pair buys. Modulo is the exception and has no such
ceiling.

Dates and intervals have their own rules and they are not symmetric. A date
plus an integer is a date and a date minus a date is a `BIGINT` of days, a
date plus an interval is a `TIMESTAMP` and not a date, a date plus a time is a
`TIMESTAMP` while a date minus a time is an error, and an interval divided by
a number is an interval while a number divided by an interval is not.

A `NULL` written in a query has no type, and it does not take the other side's
either. DuckDB picks an overload for it, so `DATE + NULL` is a `DATE` and
`NULL - DATE` is a `BIGINT`, and where two candidates tie the query is
refused rather than bound, which is what `TIME + NULL` does.
"""

from .types import (
    DECIMAL_MAX_WIDTH,
    SqlType,
    TYPE_BIGINT,
    TYPE_DATE,
    TYPE_DECIMAL,
    TYPE_DOUBLE,
    TYPE_FLOAT,
    TYPE_INTEGER,
    TYPE_INTERVAL,
    TYPE_INVALID,
    TYPE_NULL,
    TYPE_SMALLINT,
    TYPE_HUGEINT,
    TYPE_TIME,
    TYPE_TIME_NS,
    TYPE_TIME_TZ,
    TYPE_TIMESTAMP,
    TYPE_TIMESTAMP_MS,
    TYPE_TIMESTAMP_NS,
    TYPE_TIMESTAMP_S,
    TYPE_TIMESTAMP_TZ,
    TYPE_TINYINT,
    TYPE_UBIGINT,
    TYPE_UHUGEINT,
    TYPE_UINTEGER,
    TYPE_USMALLINT,
    TYPE_UTINYINT,
    type_name,
)


comptime NARROW_DECIMAL_WIDTH: UInt8 = 18
"""How many digits of decimal fit in sixty four bits.

Not a limit on the type, which goes to `DECIMAL_MAX_WIDTH`. It is the width
DuckDB narrows an addition or a multiplication back to when both operands were
inside it, rather than letting the answer spill into a wider arithmetic than
either operand needed.
"""


comptime OP_ADD: UInt8 = 0
"""`+`."""


comptime OP_SUBTRACT: UInt8 = 1
"""`-`."""


comptime OP_MULTIPLY: UInt8 = 2
"""`*`."""


comptime OP_DIVIDE: UInt8 = 3
"""`/`, which is floating point division even on two integers."""


comptime OP_INT_DIVIDE: UInt8 = 4
"""`//`, which is what integer division is spelled in this dialect."""


comptime OP_MODULO: UInt8 = 5
"""`%`."""


comptime PROMOTION_WIDTH: Int = 12
"""How many types the promotion table covers, `TINYINT` through `DOUBLE`."""


def operator_name(operator: UInt8) -> StaticString:
    """How an operator is written.

    Args:
        operator: One of the `OP_` constants.

    Returns:
        The symbol, or an empty string for an identifier that is not one.
    """
    if operator == OP_ADD:
        return "+"
    if operator == OP_SUBTRACT:
        return "-"
    if operator == OP_MULTIPLY:
        return "*"
    if operator == OP_DIVIDE:
        return "/"
    if operator == OP_INT_DIVIDE:
        return "//"
    if operator == OP_MODULO:
        return "%"
    return ""


def in_promotion_table(id: UInt8) -> Bool:
    """Whether an identifier sits in the promotion table.

    `DECIMAL` does not, because it derives its width from the operands.

    Args:
        id: One of the `TYPE_` constants.

    Returns:
        True for `TINYINT` through `DOUBLE`.
    """
    return id >= TYPE_TINYINT and id <= TYPE_DOUBLE


def promote(a: SqlType, b: SqlType) -> SqlType:
    """The type two numbers are widened to before an operator runs on them.

    Args:
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        The widened type, or an invalid type if the pair has no overload.
    """
    if not in_promotion_table(a.id) or not in_promotion_table(b.id):
        return SqlType(TYPE_INVALID)
    var row = Int(a.id) - Int(TYPE_TINYINT)
    var column = Int(b.id) - Int(TYPE_TINYINT)
    return SqlType(promotions()[row * PROMOTION_WIDTH + column])


def arithmetic_type(operator: UInt8, a: SqlType, b: SqlType) -> SqlType:
    """What an operator gives back for two operand types.

    Args:
        operator: One of the `OP_` constants.
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        The result type, or a type with `TYPE_INVALID` on it when no overload
        takes that pair and the caller should raise.
    """
    if a.id == TYPE_NULL:
        return _null_type(operator, b, True)
    if b.id == TYPE_NULL:
        return _null_type(operator, a, False)
    if _is_temporal(a.id) or _is_temporal(b.id):
        return _temporal_type(operator, a, b)
    if operator == OP_DIVIDE:
        return _division_type(a, b)
    if a.id == TYPE_DECIMAL or b.id == TYPE_DECIMAL:
        return _decimal_type(operator, a, b)
    return promote(a, b)


def negation_type(a: SqlType) -> SqlType:
    """What unary minus gives back.

    The type is unchanged, including for an unsigned integer, so `-1::UTINYINT`
    is a `UTINYINT` and overflows at runtime rather than being widened first.

    Args:
        a: The operand's type.

    Returns:
        The result type, or an invalid type when nothing negates that.
    """
    if a.id == TYPE_NULL:
        # An untyped literal has nothing to negate, so it falls back on the
        # widest signed integer the same way `NULL + NULL` does.
        return SqlType(TYPE_BIGINT)
    if a.id == TYPE_DECIMAL or a.id == TYPE_INTERVAL:
        return a
    if in_promotion_table(a.id):
        return a
    return SqlType(TYPE_INVALID)


def no_such_operator(operator: UInt8, a: SqlType, b: SqlType) -> String:
    """DuckDB's message for an operator with no overload for those types.

    DuckDB follows this with a list of every candidate overload, which is the
    whole operator table and belongs with the function registry rather than
    here, so the list is not reproduced yet.

    Args:
        operator: One of the `OP_` constants.
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        The message.
    """
    return String(
        "Binder Error: No function matches the given name and argument types",
        " '",
        operator_name(operator),
        "(",
        a.name(),
        ", ",
        b.name(),
        ")'. You might need to add explicit type casts.",
    )


def no_such_unary_operator(operator: UInt8, a: SqlType) -> String:
    """DuckDB's message for a prefix operator with no overload for that type.

    Args:
        operator: One of the `OP_` constants.
        a: The operand's type.

    Returns:
        The message.
    """
    return String(
        "Binder Error: No function matches the given name and argument types",
        " '",
        operator_name(operator),
        "(",
        a.name(),
        ")'. You might need to add explicit type casts.",
    )


def _null_type(operator: UInt8, other: SqlType, null_on_left: Bool) -> SqlType:
    """What an operator gives back when one side is an untyped `NULL`.

    A `NULL` written in a query has no type yet, and DuckDB does not give it
    the other operand's type. It picks an overload, and the answer is whatever
    that overload returns, which is lopsided in ways substitution would never
    produce: `DATE + NULL` is a `DATE` because the cheapest candidate is the
    one taking a count of days, while `NULL - DATE` is a `BIGINT` because the
    cheapest one there is a date minus a date. Where two candidates tie,
    DuckDB refuses the query rather than choosing, so `TIME + NULL` and
    `INTERVAL + NULL` are errors. Those are reported here as no overload
    rather than as an ambiguity, which is a worse message for the same
    refusal, and it stays that way until the function registry can list the
    candidates it could not choose between.

    Args:
        operator: One of the `OP_` constants.
        other: The type of the side that has one.
        null_on_left: Whether the `NULL` is the left operand.

    Returns:
        The result type, or an invalid type when no overload takes that pair.
    """
    var none = SqlType(TYPE_INVALID)
    if other.id == TYPE_NULL:
        # Two untyped literals fall back on the widest signed integer, and
        # division is the one operator that does not.
        if operator == OP_DIVIDE:
            return SqlType(TYPE_DOUBLE)
        return SqlType(TYPE_BIGINT)
    if other.id == TYPE_DECIMAL:
        if operator == OP_DIVIDE or operator == OP_INT_DIVIDE:
            return SqlType(TYPE_DOUBLE)
        # A decimal derives its width from both operands and an untyped
        # literal has none to give, so the derivation collapses and the result
        # is the NULL type rather than a decimal. That is DuckDB's answer and
        # it is not a useful one.
        return SqlType(TYPE_NULL)
    if in_promotion_table(other.id):
        # The one place substitution is right, because every numeric overload
        # takes two of the same type.
        if operator == OP_DIVIDE:
            return _division_type(other, other)
        return other
    if not _is_temporal(other.id):
        return none
    if operator == OP_MULTIPLY:
        return SqlType(TYPE_INTERVAL) if other.id == TYPE_INTERVAL else none
    if operator == OP_DIVIDE:
        if null_on_left:
            return none
        return SqlType(TYPE_INTERVAL) if other.id == TYPE_INTERVAL else none
    if operator == OP_ADD:
        # A date takes the count of days, a timestamp takes the interval, and
        # a time or an interval has two candidates and takes neither.
        if other.id == TYPE_DATE:
            return SqlType(TYPE_DATE)
        if _is_instant(other.id):
            return _shifted(other)
        return none
    if operator != OP_SUBTRACT:
        return none
    if null_on_left:
        if other.id == TYPE_INTERVAL:
            return none
        # Nothing subtracts from an untyped literal except the type itself.
        return _temporal_difference(other, other)
    if other.id == TYPE_DATE:
        return SqlType(TYPE_DATE)
    return _shifted(other)


def _is_temporal(id: UInt8) -> Bool:
    """Whether a type takes the date and interval rules.

    Args:
        id: One of the `TYPE_` constants.

    Returns:
        True for a date, a time, a timestamp or an interval.
    """
    return SqlType(id).is_temporal() or id == TYPE_INTERVAL


def _division_type(a: SqlType, b: SqlType) -> SqlType:
    """What `/` gives back, which is a float whatever went in.

    Args:
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        `FLOAT`, `DOUBLE`, or an invalid type for a pair that is not numeric.
    """
    if not a.is_numeric() or not b.is_numeric():
        return SqlType(TYPE_INVALID)
    if a.id == TYPE_DOUBLE or b.id == TYPE_DOUBLE:
        return SqlType(TYPE_DOUBLE)
    if a.id == TYPE_FLOAT or b.id == TYPE_FLOAT:
        return SqlType(TYPE_FLOAT)
    return SqlType(TYPE_DOUBLE)


def _decimal_type(operator: UInt8, a: SqlType, b: SqlType) -> SqlType:
    """What an operator gives back when one side is a decimal.

    Args:
        operator: One of the `OP_` constants, never `OP_DIVIDE`.
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        The result type, or an invalid type when the other side is not a
        number.
    """
    if a.is_float() or b.is_float():
        return _division_type(a, b)
    if operator == OP_MODULO:
        return _modulo_type(a, b)
    var left = _widen(a)
    var right = _widen(b)
    if left.id == TYPE_INVALID or right.id == TYPE_INVALID:
        return SqlType(TYPE_INVALID)
    var widest = max(left.width, right.width)
    if operator == OP_MULTIPLY:
        if left.scale + right.scale > DECIMAL_MAX_WIDTH:
            # There is no answer to give. DuckDB will not round the scale down
            # and has no wider decimal to put it in, so it refuses the call.
            # The message we print for that is the one for an operator with no
            # overload rather than DuckDB's out of range error, which names the
            # scale it wanted.
            return SqlType(TYPE_INVALID)
        return _capped(
            left.width + right.width,
            left.scale + right.scale,
            widest,
            True,
        )
    if operator == OP_INT_DIVIDE:
        # Integer division on a decimal is not a decimal at all.
        return SqlType(TYPE_DOUBLE)
    var scale = max(left.scale, right.scale)
    var digits = max(left.width - left.scale, right.width - right.scale)
    return _capped(digits + scale + 1, scale, widest, False)


def _modulo_type(a: SqlType, b: SqlType) -> SqlType:
    """What `%` gives back when one side is a decimal.

    Modulo cannot grow, since the answer is smaller than the divisor, so it
    takes the lattice join rather than deriving a width. The one thing it does
    not do is saturate: where `+` quietly narrows a result that wants more than
    thirty eight digits, `%` gives up on being exact and returns a `DOUBLE`.
    Two operators, two answers to the same overflow, and both are DuckDB's.

    Args:
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        The result type, or an invalid type when the other side is not a
        number.
    """
    var left = _widen(a)
    var right = _widen(b)
    if left.id == TYPE_INVALID or right.id == TYPE_INVALID:
        return SqlType(TYPE_INVALID)
    var scale = max(left.scale, right.scale)
    var digits = max(left.width - left.scale, right.width - right.scale)
    if Int(digits) + Int(scale) > Int(DECIMAL_MAX_WIDTH):
        return SqlType(TYPE_DOUBLE)
    return SqlType(TYPE_DECIMAL, digits + scale, scale)


def _widen(type: SqlType) -> SqlType:
    """The decimal a type counts as inside a decimal derivation.

    Args:
        type: A decimal or an integer.

    Returns:
        The decimal, or an invalid type for anything else.
    """
    if type.id == TYPE_DECIMAL:
        return type
    var width = _integer_width(type.id)
    if width == 0:
        return SqlType(TYPE_INVALID)
    return SqlType(TYPE_DECIMAL, width, 0)


def _integer_width(id: UInt8) -> UInt8:
    """How many digits an integer type needs.

    Args:
        id: One of the `TYPE_` constants.

    Returns:
        The width, or zero for a type that is not an integer.
    """
    var type = SqlType(id)
    if not type.is_integer():
        return 0
    var bits = type.bits()
    if bits == 8:
        return 3
    if bits == 16:
        return 5
    if bits == 32:
        return 10
    if bits == 64:
        return 20 if id == TYPE_UBIGINT else 19
    return DECIMAL_MAX_WIDTH


def _capped(width: UInt8, scale: UInt8, widest: UInt8, whole: Bool) -> SqlType:
    """A decimal, narrowed if the derivation asked for a wider one than exists.

    There are two ceilings and not one. The obvious one is thirty eight
    digits, which is every decimal there is. The other is eighteen, which is
    what fits in sixty four bits, and it is the one that surprises: DuckDB
    will not take a pair that both fit in sixty four bits into a hundred and
    twenty eight bit arithmetic, so `DECIMAL(18,6) + DECIMAL(18,6)` is a
    `DECIMAL(18,6)` and not the `DECIMAL(19,6)` the derivation wanted, while
    `DECIMAL(19,6) + DECIMAL(19,6)` is a `DECIMAL(20,6)` because one of those
    was already past sixty four bits. Either way DuckDB saturates rather than
    raising, so the digit the derivation asked for is simply not there.

    Args:
        width: The width the derivation wanted.
        scale: The scale it wanted.
        widest: The wider of the two operands, which is what says whether the
            sixty four bit ceiling applies at all.
        whole: Whether the narrowed decimal has to keep a digit in front of
            the point. Multiplication insists on that and leaves
            `DECIMAL(18,9) * DECIMAL(18,9)` at thirty six digits rather than
            narrowing it to `DECIMAL(18,18)`; addition does not, and
            `DECIMAL(18,18) + DECIMAL(18,1)` is a `DECIMAL(18,18)`.

    Returns:
        The type.
    """
    if (
        width > NARROW_DECIMAL_WIDTH
        and widest <= NARROW_DECIMAL_WIDTH
        and (scale < NARROW_DECIMAL_WIDTH or not whole)
    ):
        return SqlType(TYPE_DECIMAL, NARROW_DECIMAL_WIDTH, scale)
    if width > DECIMAL_MAX_WIDTH:
        return SqlType(TYPE_DECIMAL, DECIMAL_MAX_WIDTH, scale)
    return SqlType(TYPE_DECIMAL, width, scale)


def _temporal_type(operator: UInt8, a: SqlType, b: SqlType) -> SqlType:
    """What an operator gives back for a date, a time or an interval.

    Args:
        operator: One of the `OP_` constants.
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        The result type, or an invalid type when no overload takes that pair.
    """
    var none = SqlType(TYPE_INVALID)
    if operator == OP_MULTIPLY:
        # An interval scales by a number, either way round, and nothing else
        # here multiplies at all.
        if a.id == TYPE_INTERVAL and b.is_numeric():
            return SqlType(TYPE_INTERVAL)
        if b.id == TYPE_INTERVAL and a.is_numeric():
            return SqlType(TYPE_INTERVAL)
        return none
    if operator == OP_DIVIDE:
        # One way round only. A number over an interval is not defined.
        if a.id == TYPE_INTERVAL and b.is_numeric():
            return SqlType(TYPE_INTERVAL)
        return none
    if operator != OP_ADD and operator != OP_SUBTRACT:
        return none
    if a.id == TYPE_INTERVAL and b.id == TYPE_INTERVAL:
        return SqlType(TYPE_INTERVAL)
    if operator == OP_ADD:
        return _temporal_sum(a, b)
    return _temporal_difference(a, b)


def _temporal_sum(a: SqlType, b: SqlType) -> SqlType:
    """What `+` gives back for a date, a time or an interval.

    Args:
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        The result type, or an invalid type when no overload takes that pair.
    """
    var none = SqlType(TYPE_INVALID)
    if b.id == TYPE_INTERVAL:
        return _shifted(a)
    if a.id == TYPE_INTERVAL:
        return _shifted(b)
    # A date and a time make a timestamp, either way round, and the zone on
    # the time carries over onto it. Two dates do not make anything.
    if a.id == TYPE_DATE and b.id == TYPE_TIME:
        return SqlType(TYPE_TIMESTAMP)
    if a.id == TYPE_TIME and b.id == TYPE_DATE:
        return SqlType(TYPE_TIMESTAMP)
    if a.id == TYPE_DATE and b.id == TYPE_TIME_TZ:
        return SqlType(TYPE_TIMESTAMP_TZ)
    if a.id == TYPE_TIME_TZ and b.id == TYPE_DATE:
        return SqlType(TYPE_TIMESTAMP_TZ)
    # A date plus a count of days is a date, so long as the count fits in an
    # INTEGER. A BIGINT of days is not accepted and that is DuckDB's line.
    if a.id == TYPE_DATE and _counts_days(b):
        return SqlType(TYPE_DATE)
    if b.id == TYPE_DATE and _counts_days(a):
        return SqlType(TYPE_DATE)
    return none


def _temporal_difference(a: SqlType, b: SqlType) -> SqlType:
    """What `-` gives back for a date, a time or an interval.

    Args:
        a: The left operand's type.
        b: The right operand's type.

    Returns:
        The result type, or an invalid type when no overload takes that pair.
    """
    var none = SqlType(TYPE_INVALID)
    if b.id == TYPE_INTERVAL:
        return _shifted(a)
    if a.id == TYPE_INTERVAL:
        return none
    if a.id == TYPE_DATE and b.id == TYPE_DATE:
        # A count of days, and the one place subtracting two of these gives a
        # number rather than an interval.
        return SqlType(TYPE_BIGINT)
    if a.id == TYPE_DATE and _counts_days(b):
        return SqlType(TYPE_DATE)
    if _is_instant(a.id) and _is_instant(b.id):
        # Except for a zoned timestamp against one kept in another unit, where
        # DuckDB can reach the one overload by converting either side and
        # refuses to pick.
        if _is_scaled(a.id) and b.id == TYPE_TIMESTAMP_TZ:
            return none
        if a.id == TYPE_TIMESTAMP_TZ and _is_scaled(b.id):
            return none
        return SqlType(TYPE_INTERVAL)
    return none


def _shifted(a: SqlType) -> SqlType:
    """What a point in time becomes when an interval moves it.

    A date does not stay a date, because an interval carries microseconds. A
    timestamp measured in seconds, milliseconds or nanoseconds does not keep
    its unit either, because there is one overload and it takes microseconds.

    Args:
        a: The type being moved.

    Returns:
        The result type, or an invalid type for something that is not a point
        in time.
    """
    if a.id == TYPE_DATE:
        return SqlType(TYPE_TIMESTAMP)
    if _is_scaled(a.id):
        return SqlType(TYPE_TIMESTAMP)
    if a.id == TYPE_TIME or a.id == TYPE_TIME_TZ:
        return a
    if a.id == TYPE_TIMESTAMP or a.id == TYPE_TIMESTAMP_TZ:
        return a
    if a.id == TYPE_INTERVAL:
        return a
    # A nanosecond time has no arithmetic at all, not even with an interval.
    return SqlType(TYPE_INVALID)


def _is_instant(id: UInt8) -> Bool:
    """Whether a type is a point on the timeline, so two of them subtract.

    Args:
        id: One of the `TYPE_` constants.

    Returns:
        True for a date or any of the timestamps.
    """
    return (
        id == TYPE_DATE
        or id == TYPE_TIMESTAMP
        or id == TYPE_TIMESTAMP_TZ
        or id == TYPE_TIMESTAMP_S
        or id == TYPE_TIMESTAMP_MS
        or id == TYPE_TIMESTAMP_NS
    )


def _is_scaled(id: UInt8) -> Bool:
    """Whether a timestamp is kept in something other than microseconds.

    Args:
        id: One of the `TYPE_` constants.

    Returns:
        True for a timestamp in seconds, milliseconds or nanoseconds.
    """
    return (
        id == TYPE_TIMESTAMP_S
        or id == TYPE_TIMESTAMP_MS
        or id == TYPE_TIMESTAMP_NS
    )


def _counts_days(a: SqlType) -> Bool:
    """Whether an integer type can be added to a date as a count of days.

    Measured: `DATE + INTEGER` is a date and `DATE + BIGINT` is an error, so
    the line is what fits in an `INTEGER` and not what is an integer.

    Args:
        a: The operand's type.

    Returns:
        True for the integer types a date accepts.
    """
    return (
        a.id == TYPE_TINYINT
        or a.id == TYPE_SMALLINT
        or a.id == TYPE_INTEGER
        or a.id == TYPE_UTINYINT
        or a.id == TYPE_USMALLINT
    )


def promotions() -> List[UInt8]:
    """What every pair from `TINYINT` through `DOUBLE` widens to.

    Twelve rows of twelve, in identifier order, read out of DuckDB 1.5. The
    same table serves `+`, `-`, `*`, `//` and `%`, which was checked over
    every pair rather than assumed.

    Returns:
        The table, row major.
    """
    return [
        # TINYINT
        TYPE_TINYINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_DOUBLE,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # SMALLINT
        TYPE_SMALLINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_SMALLINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_DOUBLE,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # INTEGER
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_DOUBLE,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # BIGINT
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_DOUBLE,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # HUGEINT
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_DOUBLE,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # UTINYINT
        TYPE_BIGINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_UTINYINT,
        TYPE_USMALLINT,
        TYPE_UINTEGER,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # USMALLINT
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_USMALLINT,
        TYPE_USMALLINT,
        TYPE_UINTEGER,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # UINTEGER
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_UINTEGER,
        TYPE_UINTEGER,
        TYPE_UINTEGER,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # UBIGINT
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_UBIGINT,
        TYPE_UBIGINT,
        TYPE_UBIGINT,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # UHUGEINT
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_UHUGEINT,
        TYPE_UHUGEINT,
        TYPE_UHUGEINT,
        TYPE_UHUGEINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # FLOAT
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # DOUBLE
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
    ]
