"""What a type turns into when a query asks for two of them at once.

`COALESCE`, `CASE`, `UNION`, `IN` and an `IN` list all take a set of
expressions and give back one column, so each of them has to answer what the
one type is. DuckDB answers with a join over its type lattice, and the answer
is observable through `typeof()`, so it is written here rather than guessed at.

The tables below were generated by asking DuckDB 1.5 for
`typeof(coalesce(NULL::a, NULL::b))` over every pair, and two things in them
are worth knowing before reading the code.

**A signed and an unsigned integer do not join the way they should.** DuckDB
says the common type of `TINYINT` and `UHUGEINT` is `SMALLINT`, which cannot
hold a `UHUGEINT`, and a query that actually has a large value in it then
fails at runtime with a conversion error rather than at bind time. That is a
defect and it is reproduced here on purpose: a query that runs against DuckDB
has to run here, and a query that fails there has to fail here, so a lattice
that was merely correct would disagree with the thing we are compatible with.

**A decimal joins by rule and not by table.** The scale of the answer is the
larger of the two scales and the width is the larger of the two integer parts
plus that scale, so `DECIMAL(4,2)` and `DECIMAL(6,3)` give `DECIMAL(6,3)`. An
integer entering that rule counts as a decimal wide enough to hold it, which
is where `DECIMAL(4,2)` and `BIGINT` giving `DECIMAL(21,2)` comes from. The
width saturates at 38 rather than raising, which is why `DECIMAL(4,2)` and
`HUGEINT` give `DECIMAL(38,2)` and not an error.

A literal is not covered here. `coalesce('a', 1)` is an `INTEGER` in DuckDB
while `coalesce(NULL::VARCHAR, 1)` is an error, because an unadorned literal
carries a type that is still open when the binder reaches it. That belongs to
the binder rather than to the lattice and it arrives with expression binding.
"""

from .types import (
    DECIMAL_MAX_WIDTH,
    SqlType,
    TYPE_BIGINT,
    TYPE_BOOLEAN,
    TYPE_DATE,
    TYPE_DECIMAL,
    TYPE_DOUBLE,
    TYPE_FLOAT,
    TYPE_HUGEINT,
    TYPE_INTEGER,
    TYPE_INTERVAL,
    TYPE_INVALID,
    TYPE_NULL,
    TYPE_SMALLINT,
    TYPE_TIME,
    TYPE_TIME_NS,
    TYPE_TIME_TZ,
    TYPE_TIMESTAMP,
    TYPE_TIMESTAMP_MS,
    TYPE_TIMESTAMP_NS,
    TYPE_TIMESTAMP_S,
    TYPE_TIMESTAMP_TZ,
    TYPE_TINYINT,
    TYPE_UBIGINT,
    TYPE_UHUGEINT,
    TYPE_UINTEGER,
    TYPE_USMALLINT,
    TYPE_UTINYINT,
)


comptime NUMERIC_WIDTH: Int = 13
"""How many types the numeric table covers, `BOOLEAN` through `DOUBLE`."""


comptime TEMPORAL_WIDTH: Int = 10
"""How many types the temporal table covers, `DATE` through `INTERVAL`."""


def is_numeric_id(id: UInt8) -> Bool:
    """Whether an identifier sits in the numeric join table.

    `DECIMAL` does not, because it joins by rule rather than by lookup.

    Args:
        id: One of the `TYPE_` constants.

    Returns:
        True for `BOOLEAN` through `DOUBLE`.
    """
    return id >= TYPE_BOOLEAN and id <= TYPE_DOUBLE


def is_temporal_id(id: UInt8) -> Bool:
    """Whether an identifier sits in the temporal join table.

    Args:
        id: One of the `TYPE_` constants.

    Returns:
        True for `DATE` through `INTERVAL`.
    """
    return id >= TYPE_DATE and id <= TYPE_INTERVAL


def decimal_width(id: UInt8) -> UInt8:
    """How wide a decimal has to be to hold every value of an integer type.

    Measured rather than computed, because `UBIGINT` needs twenty digits where
    `BIGINT` needs nineteen, and `UHUGEINT` needs thirty nine and does not get
    it: DuckDB saturates it at thirty eight, the widest decimal there is.

    Args:
        id: One of the `TYPE_` constants.

    Returns:
        The width, or zero for a type that is not an integer.
    """
    if id == TYPE_TINYINT or id == TYPE_UTINYINT:
        return 3
    if id == TYPE_SMALLINT or id == TYPE_USMALLINT:
        return 5
    if id == TYPE_INTEGER or id == TYPE_UINTEGER:
        return 10
    if id == TYPE_BIGINT:
        return 19
    if id == TYPE_UBIGINT:
        return 20
    if id == TYPE_HUGEINT or id == TYPE_UHUGEINT:
        return DECIMAL_MAX_WIDTH
    return 0


def as_decimal(type: SqlType) -> SqlType:
    """The decimal a type counts as when it meets one.

    Args:
        type: A decimal or an integer.

    Returns:
        The type itself if it is already a decimal, the decimal wide enough to
        hold it if it is an integer, and an invalid type otherwise.
    """
    if type.id == TYPE_DECIMAL:
        return type
    var width = decimal_width(type.id)
    if width == 0:
        return SqlType(TYPE_INVALID)
    return SqlType(TYPE_DECIMAL, width, 0)


def common_type(a: SqlType, b: SqlType) -> SqlType:
    """The one type two of them agree on, or an invalid type if there is none.

    Args:
        a: One of the types.
        b: The other.

    Returns:
        The common type, or a type with `TYPE_INVALID` on it when the two do
        not mix and the caller should raise.
    """
    if a == b:
        return a
    # The NULL literal has no opinion, so it takes whatever it is next to.
    if a.id == TYPE_NULL:
        return b
    if b.id == TYPE_NULL:
        return a
    if a.id == TYPE_DECIMAL or b.id == TYPE_DECIMAL:
        return _common_decimal(a, b)
    if is_numeric_id(a.id) and is_numeric_id(b.id):
        var row = Int(a.id) - Int(TYPE_BOOLEAN)
        var column = Int(b.id) - Int(TYPE_BOOLEAN)
        return SqlType(numeric_joins()[row * NUMERIC_WIDTH + column])
    if is_temporal_id(a.id) and is_temporal_id(b.id):
        var row = Int(a.id) - Int(TYPE_DATE)
        var column = Int(b.id) - Int(TYPE_DATE)
        return SqlType(temporal_joins()[row * TEMPORAL_WIDTH + column])
    if a.id == b.id:
        return SqlType(a.id)
    return SqlType(TYPE_INVALID)


def _common_decimal(a: SqlType, b: SqlType) -> SqlType:
    """The decimal, or float, two types agree on when one of them is a decimal.

    A decimal meeting a binary float gives the float, which is the one place
    the exactness a decimal exists for is thrown away, and DuckDB throws it
    away rather than raising.

    Args:
        a: One of the types.
        b: The other.

    Returns:
        The common type, or an invalid type when the other is not a number.
    """
    if a.id == TYPE_FLOAT or b.id == TYPE_FLOAT:
        return SqlType(TYPE_FLOAT)
    if a.id == TYPE_DOUBLE or b.id == TYPE_DOUBLE:
        return SqlType(TYPE_DOUBLE)
    var left = as_decimal(a)
    var right = as_decimal(b)
    if left.id == TYPE_INVALID or right.id == TYPE_INVALID:
        return SqlType(TYPE_INVALID)
    var scale = max(left.scale, right.scale)
    var digits = max(left.width - left.scale, right.width - right.scale)
    var width = digits + scale
    if width > DECIMAL_MAX_WIDTH:
        width = DECIMAL_MAX_WIDTH
        if a.id == TYPE_DECIMAL and b.id == TYPE_DECIMAL:
            # Two decimals that do not fit give up their scale rather than
            # their digits in front of the point, so `DECIMAL(18,18)` and
            # `DECIMAL(38,10)` agree on `DECIMAL(38,10)` and eight digits
            # after the point are gone. An integer against a decimal does not
            # do that. It keeps the decimal's scale and takes whatever width
            # is left for itself, so `HUGEINT` and `DECIMAL(4,2)` agree on
            # `DECIMAL(38,2)` and not on `DECIMAL(38,0)`, which is the same
            # two numbers arriving at different answers depending on which of
            # them was written as an integer.
            scale = width - digits
    return SqlType(TYPE_DECIMAL, width, scale)


def cannot_mix(a: SqlType, b: SqlType, operator: StringSlice) -> String:
    """DuckDB's message for two types that have nothing in common.

    Args:
        a: One of the types.
        b: The other.
        operator: What was asked to mix them, such as `COALESCE`.

    Returns:
        The message.
    """
    return String(
        "Binder Error: Cannot mix values of type ",
        a.name(),
        " and ",
        b.name(),
        " in ",
        operator,
        " operator - an explicit cast is required",
    )


def numeric_joins() -> List[UInt8]:
    """The common type of every pair from `BOOLEAN` through `DOUBLE`.

    Thirteen rows of thirteen, in identifier order, read out of DuckDB 1.5.
    `TYPE_INVALID` means the pair does not mix, which is a boolean meeting a
    binary float and nothing else.

    Returns:
        The table, row major.
    """
    return [
        # BOOLEAN
        TYPE_BOOLEAN,
        TYPE_TINYINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_UTINYINT,
        TYPE_USMALLINT,
        TYPE_UINTEGER,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_INVALID,
        TYPE_INVALID,
        # TINYINT
        TYPE_TINYINT,
        TYPE_TINYINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_SMALLINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # SMALLINT
        TYPE_SMALLINT,
        TYPE_SMALLINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_INTEGER,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # INTEGER
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_BIGINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # BIGINT
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # HUGEINT
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_DOUBLE,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # UTINYINT
        TYPE_UTINYINT,
        TYPE_SMALLINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_UTINYINT,
        TYPE_USMALLINT,
        TYPE_UINTEGER,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # USMALLINT
        TYPE_USMALLINT,
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_USMALLINT,
        TYPE_USMALLINT,
        TYPE_UINTEGER,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # UINTEGER
        TYPE_UINTEGER,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_UINTEGER,
        TYPE_UINTEGER,
        TYPE_UINTEGER,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # UBIGINT
        TYPE_UBIGINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_HUGEINT,
        TYPE_UBIGINT,
        TYPE_UBIGINT,
        TYPE_UBIGINT,
        TYPE_UBIGINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # UHUGEINT
        TYPE_UHUGEINT,
        TYPE_SMALLINT,
        TYPE_INTEGER,
        TYPE_BIGINT,
        TYPE_HUGEINT,
        TYPE_DOUBLE,
        TYPE_UHUGEINT,
        TYPE_UHUGEINT,
        TYPE_UHUGEINT,
        TYPE_UHUGEINT,
        TYPE_UHUGEINT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # FLOAT
        TYPE_INVALID,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_FLOAT,
        TYPE_DOUBLE,
        # DOUBLE
        TYPE_INVALID,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
        TYPE_DOUBLE,
    ]


def temporal_joins() -> List[UInt8]:
    """The common type of every pair from `DATE` through `INTERVAL`.

    Ten rows of ten, in identifier order, read out of DuckDB 1.5. A `TIME` and
    a `TIME_NS` do not mix, and neither do a `DATE` and a `TIME`, both of which
    look like oversights and both of which are what DuckDB does.

    Returns:
        The table, row major.
    """
    return [
        # DATE
        TYPE_DATE,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_TIMESTAMP,
        TYPE_TIMESTAMP_TZ,
        TYPE_TIMESTAMP_S,
        TYPE_TIMESTAMP_MS,
        TYPE_TIMESTAMP_NS,
        TYPE_INVALID,
        TYPE_INVALID,
        # TIME
        TYPE_INVALID,
        TYPE_TIME,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        # TIME WITH TIME ZONE
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_TIME_TZ,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        # TIMESTAMP
        TYPE_TIMESTAMP,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_TIMESTAMP,
        TYPE_TIMESTAMP_TZ,
        TYPE_TIMESTAMP,
        TYPE_TIMESTAMP,
        TYPE_TIMESTAMP_NS,
        TYPE_INVALID,
        TYPE_INVALID,
        # TIMESTAMP WITH TIME ZONE
        TYPE_TIMESTAMP_TZ,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_TIMESTAMP_TZ,
        TYPE_TIMESTAMP_TZ,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        # TIMESTAMP_S
        TYPE_TIMESTAMP_S,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_TIMESTAMP,
        TYPE_INVALID,
        TYPE_TIMESTAMP_S,
        TYPE_TIMESTAMP_MS,
        TYPE_TIMESTAMP_NS,
        TYPE_INVALID,
        TYPE_INVALID,
        # TIMESTAMP_MS
        TYPE_TIMESTAMP_MS,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_TIMESTAMP,
        TYPE_INVALID,
        TYPE_TIMESTAMP_MS,
        TYPE_TIMESTAMP_MS,
        TYPE_TIMESTAMP_NS,
        TYPE_INVALID,
        TYPE_INVALID,
        # TIMESTAMP_NS
        TYPE_TIMESTAMP_NS,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_TIMESTAMP_NS,
        TYPE_INVALID,
        TYPE_TIMESTAMP_NS,
        TYPE_TIMESTAMP_NS,
        TYPE_TIMESTAMP_NS,
        TYPE_INVALID,
        TYPE_INVALID,
        # TIME_NS
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_TIME_NS,
        TYPE_INVALID,
        # INTERVAL
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INVALID,
        TYPE_INTERVAL,
    ]
