"""The table every `\\p{...}` name is read against, checked against RE2 itself.

The other six regular expression differentials compare a decision. This one
compares data, and it is here because document 115 found that the data was
wrong in a way none of the other six could see.

The table in `firepanda/kernel/regex/unicodedata.mojo` is 200 names and 5820
ranges, generated by asking the RE2 inside pyarrow about every code point there
is, one name at a time. That was measured once, against one release, and has
been carried in the repository ever since. Nothing checked it afterwards. A
pattern in the corpus that names a category proves the name is found and the
ranges are emitted, and proves nothing whatever about whether the ranges are the
ranges RE2 has, because the corpus runs against a hundred texts and a name is a
set of a million code points.

Regenerating the table and finding the file unchanged is the honest check and it
is also a few minutes of compute, which is why nobody runs it. This is the same
check made cheap. A range table is wrong at its edges or it is not wrong at all:
a low that is one too low, a high that is one too high, a range that should have
been two. So the four code points around each range are asked about rather than
every code point inside it, which is 18834 questions rather than 1112064, and
the run takes about half a second against a warm build.

What it cannot see is a range that is entirely missing from a name this library
has, since there is no edge to ask about. What catches that is the generator,
which asks RE2 about every code point and writes the whole set. What catches a
name missing altogether is the sweep in the generator, added by document 115.
Between the three of them the table is covered, and this is the one of the three
that is cheap enough to run after a change.

The ceiling is zero. A wrong range is not a refusal a caller can see, it is a
column of booleans that looks exactly like a right one.

Usage:
    pixi run differential-regex-property
"""

from std.python import Python, PythonObject

from firepanda.kernel.regex.unicodedata import (
    UNICODE_NAME_AT,
    UNICODE_NAMES,
    unicode_holds,
    unicode_index,
    unicode_ranges,
)

comptime SHOWN = 30
"""How many disagreements are printed before the rest are counted.

The same number the corpus prints, and for the same reason: a table that has
drifted has drifted in a shape, and the shape is in the first few lines.
"""

comptime SURROGATE_LOW = 0xD800
"""The first code point no row can hold.

A surrogate has no UTF-8 encoding, so a column cannot be built holding one and
the question cannot be put to RE2 at all. The generator left them out for the
same reason.
"""

comptime SURROGATE_HIGH = 0xDFFF
"""The last of them."""

comptime LAST = 0x10FFFF
"""The largest code point there is."""

comptime STAND_IN = 0x61
"""What to ask about for a name with no ranges under it.

`Cs` is the only one, it covers the surrogates and a row cannot hold one, so
there is no edge to ask about and the only thing left worth asking is whether
RE2 still reads the name. A letter does that: the answer has to be no, and a
name RE2 has lost answers with a refusal instead.
"""


def every_name() -> List[String]:
    """Every name in the table, in the order the table holds them.

    Returns:
        The names.
    """
    var at = materialize[UNICODE_NAME_AT]()
    var out = List[String]()
    for which in range(len(at) - 1):
        out.append(
            String(UNICODE_NAMES[byte = Int(at[which]) : Int(at[which + 1])])
        )
    return out^


def put(mut out: List[UInt32], point: Int):
    """Adds one code point to ask about, if it is one that can be asked about.

    Duplicates are dropped by looking at the last one rather than by searching,
    which is enough because the ranges arrive in order and so do the four points
    taken around each of them.

    Args:
        out: The points so far.
        point: The candidate.
    """
    if point < 0 or point > LAST:
        return
    if point >= SURROGATE_LOW and point <= SURROGATE_HIGH:
        return
    if len(out) > 0 and out[len(out) - 1] == UInt32(point):
        return
    out.append(UInt32(point))


def edges(which: Int32) -> List[UInt32]:
    """The code points to ask about for one name.

    Four per range, which are the two ends and the code point outside each of
    them. The ones outside are the half that matters: a range whose ends are
    both right can still be one that swallowed the character next to it.

    Args:
        which: The name's index in the table.

    Returns:
        The points, in order and without repeats.
    """
    var ranges = unicode_ranges(which)
    var out = List[UInt32]()
    for at in range(0, len(ranges), 2):
        var low = Int(ranges[at])
        var high = Int(ranges[at + 1])
        put(out, low - 1)
        put(out, low)
        put(out, high)
        put(out, high + 1)
    if len(out) == 0:
        out.append(UInt32(STAND_IN))
    return out^


def ask_re2(rows: List[String]) raises -> List[String]:
    """What RE2 says about every name.

    One call across the boundary for the whole table, the way the other
    differentials send a whole corpus, because the crossing costs more than the
    work on either side of it.

    Args:
        rows: One per name, each the name and then its code points in decimal.

    Returns:
        One line per name, each either a single `x` or one letter per point.

    Raises:
        Error: If the helper could not be reached, or answered the wrong number
            of times.
    """
    var batch = Python.list()
    for row in rows:
        batch.append(PythonObject(row))

    var python_path = Python.import_module("sys").path
    python_path.insert(0, "tools")
    var helper = Python.import_module("regex_property_oracle")

    var out = List[String]()
    for line in String(helper.answers(batch)).split("\n"):
        out.append(String(line))
    if len(out) != len(rows):
        raise Error(
            String(
                "RE2 answered about ",
                len(out),
                " names and there are ",
                len(rows),
            )
        )
    return out^


def main() raises:
    var names = every_name()
    var wanted = List[List[UInt32]]()
    var rows = List[String]()
    var points = 0
    for name in names:
        var asked = edges(unicode_index(name))
        var row = name.copy()
        for point in asked:
            row += String(" ", Int(point))
        points += len(asked)
        wanted.append(asked^)
        rows.append(row^)

    print("asking RE2 about", len(names), "names over", points, "code points")
    var answers = ask_re2(rows)

    var differ = List[String]()
    var refused = List[String]()
    for at in range(len(names)):
        ref name = names[at]
        ref answer = answers[at]
        if answer == "x":
            refused.append(name)
            continue
        var which = unicode_index(name)
        for step in range(len(wanted[at])):
            var point = wanted[at][step]
            var theirs = answer[byte=step] == "y"
            var ours = unicode_holds(which, point)
            if ours != theirs:
                differ.append(
                    String(
                        "\\p{",
                        name,
                        "} at ",
                        Int(point),
                        " is ",
                        "in" if ours else "out",
                        " here and ",
                        "in" if theirs else "out",
                        " in RE2",
                    )
                )

    print()
    print("compared", len(names) - len(refused), "names")
    if len(refused) > 0:
        print(len(refused), "names RE2 no longer reads")
        for at in range(len(refused)):
            print("   ", refused[at])
    if len(differ) > 0:
        print()
        print(len(differ), "of", points, "code points answered differently")
        var shown = len(differ) if len(differ) < SHOWN else SHOWN
        for at in range(shown):
            print("   ", differ[at])
        if len(differ) > shown:
            print("   ", len(differ) - shown, "more")

    var disagreements = len(differ) + len(refused)
    print(
        "agreement",
        (points - disagreements) * 10000 // points,
        "in ten thousand,",
        disagreements,
        "disagreements",
    )

    if disagreements != 0:
        raise Error(
            String(
                disagreements,
                (
                    " disagreements about what a name covers, against a ceiling"
                    " of zero"
                ),
            )
        )
