# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""Stubs for the compiled extension, which is private.

The public API is `firepanda`, whose annotations are inline.
"""

class DataFrame:
    def length(self) -> int:
        """The number of rows."""
        ...
    def width(self) -> int:
        """The number of columns."""
        ...
    def names(self) -> list[str]:
        """The column names, in order."""
        ...
    def head(self, n: int) -> DataFrame:
        """The first n rows."""
        ...
    def tail(self, n: int) -> DataFrame:
        """The last n rows."""
        ...

def read_csv(path: str) -> DataFrame:
    """Reads a CSV file into a frame."""
    ...

def version() -> str:
    """The version the extension was built from."""
    ...
