# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""Stubs for the compiled extension, which is private.

The public API is `firepanda`, whose annotations are inline.
"""

class DataFrame:
    def __init__(self, data: object) -> None:
        """Builds one. The Python layer owns the pandas signature."""
        ...

    def length(self) -> int:
        """The number of rows."""
        ...
    def width(self) -> int:
        """The number of columns."""
        ...
    def names(self) -> list[str]:
        """The column names, in order."""
        ...
    def head(self, n: int) -> DataFrame:
        """The first n rows."""
        ...
    def tail(self, n: int) -> DataFrame:
        """The last n rows."""
        ...
    def column(self, name: str) -> Series:
        """One column, as a series."""
        ...
    def select(self, names: list[str]) -> DataFrame:
        """Several columns, as a frame."""
        ...
    def labels(self) -> Index:
        """The row labels, as an index."""
        ...
    def binary_frame(
        self, other: DataFrame, op: str, flip: bool, fill_value: object | None
    ) -> DataFrame:
        """An operation between two frames, aligning on both axes."""
        ...
    def binary_series(self, other: Series, op: str, axis: int, flip: bool) -> DataFrame:
        """An operation between a frame and a series, along one axis."""
        ...
    def binary_value(self, other: object, op: str, flip: bool) -> DataFrame:
        """An operation between every cell of a frame and one constant."""
        ...
    def compare_frame(self, other: DataFrame, op: str) -> DataFrame:
        """A comparison between two frames labelled the same on both axes."""
        ...
    def unary(self, op: str) -> DataFrame:
        """One of the four unary operations, over every column."""
        ...
    def arrow_c_schema(self) -> object:
        """The frame's Arrow schema, in a capsule."""
        ...
    def arrow_c_array(self, requested_schema: object | None) -> list[object]:
        """The frame's Arrow schema and data, in two capsules."""
        ...
    def arrow_c_stream(self, requested_schema: object | None) -> object:
        """The frame as an Arrow stream, in a capsule."""
        ...

class Series:
    def __init__(self, data: object, name: str) -> None:
        """Builds one. The Python layer owns the pandas signature."""
        ...

    def length(self) -> int:
        """The number of rows."""
        ...
    def label(self) -> str:
        """The name of the column."""
        ...
    def dtype(self) -> str:
        """The type, as firepanda spells it."""
        ...
    def null_count(self) -> int:
        """How many rows are missing."""
        ...
    def head(self, n: int) -> Series:
        """The first n rows."""
        ...
    def tail(self, n: int) -> Series:
        """The last n rows."""
        ...
    def to_list(self) -> list[object]:
        """Every value, copied into a Python list."""
        ...
    def labels(self) -> Index:
        """The row labels, as an index."""
        ...
    def binary_series(
        self, other: Series, op: str, flip: bool, fill_value: object | None
    ) -> Series:
        """An operation between two series, matching rows by label."""
        ...
    def binary_value(self, other: object, op: str, flip: bool) -> Series:
        """An operation between every row of a series and one constant."""
        ...
    def compare_series(self, other: Series, op: str) -> Series:
        """A comparison between two series labelled the same."""
        ...
    def unary(self, op: str) -> Series:
        """One of the four unary operations, over every row."""
        ...
    def arrow_c_schema(self) -> object:
        """The column's Arrow schema, in a capsule."""
        ...
    def arrow_c_array(self, requested_schema: object | None) -> list[object]:
        """The column's Arrow schema and data, in two capsules."""
        ...

class Index:
    def __init__(self, data: object, name: object) -> None:
        """Builds one. The Python layer owns the pandas signature."""
        ...

    def length(self) -> int:
        """The number of labels."""
        ...
    def label(self) -> str | None:
        """The level name, or None."""
        ...
    def dtype(self) -> str:
        """The type of the labels, as firepanda spells it."""
        ...
    def inferred_type(self) -> str:
        """What pandas calls the kind of the labels."""
        ...
    def is_range(self) -> bool:
        """Whether the labels are still an arithmetic range."""
        ...
    def start(self) -> int:
        """The first label of a range."""
        ...
    def nbytes(self) -> int:
        """The bytes the labels occupy."""
        ...
    def null_count(self) -> int:
        """How many labels are missing."""
        ...
    def at(self, i: int) -> object:
        """One label, as a Python value."""
        ...
    def to_list(self) -> list[object]:
        """Every label, copied into a Python list."""
        ...
    def slice_rows(self, start: int, end: int) -> Index:
        """A half open range of rows."""
        ...
    def take(self, positions: list[int]) -> Index:
        """Labels gathered by position."""
        ...
    def is_unique(self) -> bool:
        """Whether every label appears once."""
        ...
    def is_monotonic_increasing(self) -> bool:
        """Whether the labels never decrease."""
        ...
    def is_monotonic_decreasing(self) -> bool:
        """Whether the labels never increase."""
        ...
    def get_loc(self, label: object) -> list[int]:
        """Every position one label sits at."""
        ...
    def get_indexer(self, target: object) -> list[int]:
        """Where each of a set of labels sits, with -1 for the missing."""
        ...
    def contains(self, label: object) -> bool:
        """Whether a label is in the index."""
        ...
    def equals(self, other: object) -> bool:
        """Whether two indexes hold the same labels."""
        ...
    def identical(self, other: object) -> bool:
        """Whether the labels and the name both match."""
        ...
    def same_as(self, other: object) -> bool:
        """Whether two indexes are the same object underneath."""
        ...
    def unique(self) -> Index:
        """The first of each label."""
        ...
    def renamed(self, name: str | None) -> Index:
        """The index under a different level name."""
        ...
    def union(self, other: object, sort: bool) -> Index:
        """Every label either side has."""
        ...
    def intersection(self, other: object, sort: bool) -> Index:
        """Every label both sides have."""
        ...
    def difference(self, other: object, sort: bool) -> Index:
        """Every label this index has and the other does not."""
        ...
    def symmetric_difference(self, other: object, sort: bool, result_name: str | None) -> Index:
        """Every label exactly one side has."""
        ...
    def append(self, others: list[object]) -> Index:
        """One or several indexes put on the end of this one."""
        ...
    def delete(self, positions: list[int]) -> Index:
        """The index without the labels at a set of positions."""
        ...
    def insert(self, position: int, label: object) -> Index:
        """The index with one label put in at a position."""
        ...
    def drop(self, labels: object, errors: str) -> Index:
        """The index without every row carrying one of a set of labels."""
        ...
    def putmask(self, mask: list[bool], value: object) -> Index:
        """The index with the labels a mask picks out replaced."""
        ...
    def get_slice_bound(self, label: object, side: str) -> int:
        """Where a label sits when the index is read in order."""
        ...
    def slice_locs(self, start: object, end: object) -> list[int]:
        """The half open row range a pair of labels describes."""
        ...
    def slice_indexer(self, start: object, end: object, step: int) -> list[int]:
        """The same range with the step carried through."""
        ...
    def arrow_c_schema(self) -> object:
        """The labels' Arrow schema, in a capsule."""
        ...
    def arrow_c_array(self, requested_schema: object | None) -> list[object]:
        """The labels' Arrow schema and data, in two capsules."""
        ...

def read_csv(path: str) -> DataFrame:
    """Reads a CSV file into a frame."""
    ...

def from_arrow(source: object) -> DataFrame:
    """Builds a frame from a pyarrow, Polars or pandas frame."""
    ...

def _raise_for_test(kind: str) -> object:
    """Raises one classified error of the given kind. For tests only."""
    ...

def version() -> str:
    """The version the extension was built from."""
    ...
