# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""Stubs for the compiled extension, which is private.

The public API is `firepanda`, whose annotations are inline.
"""

class DataFrame:
    def __init__(self, data: object) -> None:
        """Builds one. The Python layer owns the pandas signature."""
        ...

    def length(self) -> int:
        """The number of rows."""
        ...
    def width(self) -> int:
        """The number of columns."""
        ...
    def names(self) -> list[str]:
        """The column names, in order."""
        ...
    def head(self, n: int) -> DataFrame:
        """The first n rows."""
        ...
    def tail(self, n: int) -> DataFrame:
        """The last n rows."""
        ...
    def column(self, name: str) -> Series:
        """One column, as a series."""
        ...
    def select(self, names: list[str]) -> DataFrame:
        """Several columns, as a frame."""
        ...
    def reduce(self, kind: str, param: float) -> Series:
        """Every column reduced to one value, as a series of them."""
        ...
    def transform(self, kind: str, periods: int) -> DataFrame:
        """Every column put through one named transformation."""
        ...
    def window_agg(
        self,
        kind: str,
        window: int | None,
        min_periods: int | None,
        center: bool,
        closed: str,
        step: int | None,
        settings: tuple[object, ...],
    ) -> DataFrame:
        """One reduction over every window of every column."""
        ...
    def dropna(self, subset: list[str]) -> DataFrame:
        """The rows with no missing value in them."""
        ...
    def cast(self, names: list[str], dtypes: list[str], strict: bool) -> DataFrame:
        """Some columns converted to other types, as a new frame."""
        ...
    def group_agg(
        self, by: list[str], kind: str, param: float, dropna: bool, sort: bool, as_index: bool
    ) -> DataFrame:
        """One reduction applied to every column that is not a key."""
        ...
    def labels(self) -> Index:
        """The row labels, as an index."""
        ...
    def binary_frame(
        self, other: DataFrame, op: str, flip: bool, fill_value: object | None
    ) -> DataFrame:
        """An operation between two frames, aligning on both axes."""
        ...
    def binary_series(self, other: Series, op: str, axis: int, flip: bool) -> DataFrame:
        """An operation between a frame and a series, along one axis."""
        ...
    def binary_value(self, other: object, op: str, flip: bool) -> DataFrame:
        """An operation between every cell of a frame and one constant."""
        ...
    def compare_frame(self, other: DataFrame, op: str) -> DataFrame:
        """A comparison between two frames labelled the same on both axes."""
        ...
    def unary(self, op: str) -> DataFrame:
        """One of the four unary operations, over every column."""
        ...
    def arrow_c_schema(self) -> object:
        """The frame's Arrow schema, in a capsule."""
        ...
    def arrow_c_array(self, requested_schema: object | None) -> list[object]:
        """The frame's Arrow schema and data, in two capsules."""
        ...
    def arrow_c_stream(self, requested_schema: object | None) -> object:
        """The frame as an Arrow stream, in a capsule."""
        ...

class Series:
    def __init__(self, data: object, name: str) -> None:
        """Builds one. The Python layer owns the pandas signature."""
        ...

    def length(self) -> int:
        """The number of rows."""
        ...
    def label(self) -> str:
        """The name of the column."""
        ...
    def relabel(self, name: str) -> Series:
        """A copy of the column under a different name."""
        ...
    def dtype(self) -> str:
        """The type, as firepanda spells it."""
        ...
    def null_count(self) -> int:
        """How many rows are missing."""
        ...
    def head(self, n: int) -> Series:
        """The first n rows."""
        ...
    def tail(self, n: int) -> Series:
        """The last n rows."""
        ...
    def to_list(self) -> list[object]:
        """Every value, copied into a Python list."""
        ...
    def labels(self) -> Index:
        """The row labels, as an index."""
        ...
    def reduce(self, kind: str, param: float) -> object:
        """The whole column reduced to one Python value."""
        ...
    def transform(self, kind: str, periods: int) -> Series:
        """The column put through one named transformation."""
        ...
    def cast(self, dtype: str, strict: bool) -> Series:
        """The column converted to another type."""
        ...
    def categories(self) -> Index:
        """A category column's categories, as an index."""
        ...
    def codes(self) -> Series:
        """The codes of a category column, as positions."""
        ...
    def ordered(self) -> bool:
        """Whether the categories have a meaningful order."""
        ...
    def set_ordered(self, ordered: bool) -> Series:
        """The same categories, ordered or not."""
        ...
    def relabel_categories(self, names: list[str], ordered: bool) -> Series:
        """New labels for the categories, matched by position."""
        ...
    def recategorize(self, names: list[str], ordered: bool) -> Series:
        """New categories, matched by value."""
        ...
    def drop_unused_categories(self) -> Series:
        """Only the categories that appear in the values."""
        ...
    def monotonic(self, increasing: bool) -> bool:
        """Whether the column is sorted, one way or the other."""
        ...
    def string_text(
        self, kind: str, arg: str, start: int | None, stop: int | None, step: int
    ) -> Series:
        """One str accessor method that answers text, as a column."""
        ...
    def window_agg(
        self,
        kind: str,
        window: int | None,
        min_periods: int | None,
        center: bool,
        closed: str,
        step: int | None,
        settings: tuple[object, ...],
    ) -> Series:
        """One reduction over every window of the column."""
        ...
    def string_flag(self, kind: str, arg: str) -> Series:
        """One str accessor method that answers a mask, as a column."""
        ...
    def string_number(self, kind: str, arg: str, start: int | None, stop: int | None) -> Series:
        """One str accessor method that answers a number, as a column."""
        ...
    def string_is_text(self) -> bool:
        """Whether the column holds text at all."""
        ...
    def temporal_part(self, kind: str, arg: str) -> Series:
        """One part of a temporal column, as a column."""
        ...
    def temporal_word(self, kind: str) -> str:
        """The clock or the resolution of a temporal column, as a string."""
        ...
    def to_datetime(self, format: str, unit: str, coerce: bool, utc: bool) -> Series:
        """A column of text or of whole numbers read as a column of instants."""
        ...
    def binary_series(
        self, other: Series, op: str, flip: bool, fill_value: object | None
    ) -> Series:
        """An operation between two series, matching rows by label."""
        ...
    def binary_value(self, other: object, op: str, flip: bool) -> Series:
        """An operation between every row of a series and one constant."""
        ...
    def compare_series(self, other: Series, op: str) -> Series:
        """A comparison between two series labelled the same."""
        ...
    def unary(self, op: str) -> Series:
        """One of the four unary operations, over every row."""
        ...
    def arrow_c_schema(self) -> object:
        """The column's Arrow schema, in a capsule."""
        ...
    def arrow_c_array(self, requested_schema: object | None) -> list[object]:
        """The column's Arrow schema and data, in two capsules."""
        ...

class Index:
    def __init__(self, data: object, name: object) -> None:
        """Builds one. The Python layer owns the pandas signature."""
        ...

    def length(self) -> int:
        """The number of labels."""
        ...
    def label(self) -> str | None:
        """The level name, or None."""
        ...
    def dtype(self) -> str:
        """The type of the labels, as firepanda spells it."""
        ...
    def inferred_type(self) -> str:
        """What pandas calls the kind of the labels."""
        ...
    def is_range(self) -> bool:
        """Whether the labels are still an arithmetic range."""
        ...
    def start(self) -> int:
        """The first label of a range."""
        ...
    def nbytes(self) -> int:
        """The bytes the labels occupy."""
        ...
    def null_count(self) -> int:
        """How many labels are missing."""
        ...
    def at(self, i: int) -> object:
        """One label, as a Python value."""
        ...
    def to_list(self) -> list[object]:
        """Every label, copied into a Python list."""
        ...
    def slice_rows(self, start: int, end: int) -> Index:
        """A half open range of rows."""
        ...
    def take(self, positions: list[int]) -> Index:
        """Labels gathered by position."""
        ...
    def is_unique(self) -> bool:
        """Whether every label appears once."""
        ...
    def is_monotonic_increasing(self) -> bool:
        """Whether the labels never decrease."""
        ...
    def is_monotonic_decreasing(self) -> bool:
        """Whether the labels never increase."""
        ...
    def get_loc(self, label: object) -> list[int]:
        """Every position one label sits at."""
        ...
    def get_indexer(self, target: object) -> list[int]:
        """Where each of a set of labels sits, with -1 for the missing."""
        ...
    def contains(self, label: object) -> bool:
        """Whether a label is in the index."""
        ...
    def equals(self, other: object) -> bool:
        """Whether two indexes hold the same labels."""
        ...
    def identical(self, other: object) -> bool:
        """Whether the labels and the name both match."""
        ...
    def same_as(self, other: object) -> bool:
        """Whether two indexes are the same object underneath."""
        ...
    def unique(self) -> Index:
        """The first of each label."""
        ...
    def renamed(self, name: str | None) -> Index:
        """The index under a different level name."""
        ...
    def union(self, other: object, sort: bool) -> Index:
        """Every label either side has."""
        ...
    def intersection(self, other: object, sort: bool) -> Index:
        """Every label both sides have."""
        ...
    def difference(self, other: object, sort: bool) -> Index:
        """Every label this index has and the other does not."""
        ...
    def symmetric_difference(self, other: object, sort: bool, result_name: str | None) -> Index:
        """Every label exactly one side has."""
        ...
    def append(self, others: list[object]) -> Index:
        """One or several indexes put on the end of this one."""
        ...
    def delete(self, positions: list[int]) -> Index:
        """The index without the labels at a set of positions."""
        ...
    def insert(self, position: int, label: object) -> Index:
        """The index with one label put in at a position."""
        ...
    def drop(self, labels: object, errors: str) -> Index:
        """The index without every row carrying one of a set of labels."""
        ...
    def putmask(self, mask: list[bool], value: object) -> Index:
        """The index with the labels a mask picks out replaced."""
        ...
    def get_slice_bound(self, label: object, side: str) -> int:
        """Where a label sits when the index is read in order."""
        ...
    def slice_locs(self, start: object, end: object) -> list[int]:
        """The half open row range a pair of labels describes."""
        ...
    def slice_indexer(self, start: object, end: object, step: int) -> list[int]:
        """The same range with the step carried through."""
        ...
    def arrow_c_schema(self) -> object:
        """The labels' Arrow schema, in a capsule."""
        ...
    def arrow_c_array(self, requested_schema: object | None) -> list[object]:
        """The labels' Arrow schema and data, in two capsules."""
        ...

def read_csv(path: str) -> DataFrame:
    """Reads a CSV file into a frame."""
    ...

def from_arrow(source: object) -> DataFrame:
    """Builds a frame from a pyarrow, Polars or pandas frame."""
    ...

def _isocalendar(column: object) -> DataFrame:
    """The ISO 8601 year, week and day of a temporal column, as a frame."""
    ...

def _raise_for_test(kind: str) -> object:
    """Raises one classified error of the given kind. For tests only."""
    ...

def version() -> str:
    """The version the extension was built from."""
    ...
