# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""The pandas surface.

Every class here holds an extension object and delegates to it. The reason
it is not the extension object itself is document 13: a bound Mojo type
cannot carry a property, an operator or a dunder, cannot be subclassed and
has no __dict__, so 28 percent of pandas is unreachable from there.

Every delegation is wrapped, because a Mojo error arrives as a bare
Exception and `errors.translate` is what puts the class back. The try costs
nothing when nothing raises, which is measured in document 14.
"""

from __future__ import annotations

from collections.abc import Sequence

from . import _firepanda
from ._pandas import DataFrameMixin, IndexMixin, SeriesMixin
from .errors import translate

__all__ = ["DataFrame", "Index", "Series"]


class DataFrame(DataFrameMixin):
    """A two dimensional labelled data structure with columns of potentially different
    types.
    """

    __slots__ = ()

    @classmethod
    def _wrap(cls, inner: _firepanda.DataFrame) -> DataFrame:
        """Puts the wrapper around an extension object.

        Not a public entry point. It allocates without going through
        __init__ because __init__ is the pandas constructor, which takes
        data rather than an extension object.
        """
        self = object.__new__(cls)
        self._inner = inner
        return self

    def __len__(self) -> int:
        """The number of rows, so that len(df) works."""
        try:
            return self._inner.length()
        except Exception as error:
            raise translate(error) from None

    def __repr__(self) -> str:
        """The frame, rendered."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    def __str__(self) -> str:
        """The frame, rendered. Same as repr, which is what pandas does."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    @property
    def columns(self) -> list[str]:
        """The column labels of the frame."""
        try:
            return self._inner.names()
        except Exception as error:
            raise translate(error) from None

    @property
    def shape(self) -> tuple[int, int]:
        """A tuple of the number of rows and the number of columns."""
        try:
            return (self._inner.length(), self._inner.width())
        except Exception as error:
            raise translate(error) from None

    @property
    def index(self) -> Index:
        """The row labels of the frame."""
        try:
            return Index._wrap(self._inner.labels())
        except Exception as error:
            raise translate(error) from None

    def head(self, n: int = 5) -> DataFrame:
        """The first n rows."""
        try:
            return DataFrame._wrap(self._inner.head(n))
        except Exception as error:
            raise translate(error) from None

    def tail(self, n: int = 5) -> DataFrame:
        """The last n rows."""
        try:
            return DataFrame._wrap(self._inner.tail(n))
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_schema__(self) -> object:
        """The frame's Arrow schema, as an arrow_schema PyCapsule."""
        try:
            return self._inner.arrow_c_schema()
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, ...]:
        """The frame's Arrow data, as an arrow_schema and an arrow_array PyCapsule."""
        try:
            return tuple(self._inner.arrow_c_array(requested_schema))
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object:
        """The frame as a stream of one batch, as an arrow_array_stream PyCapsule."""
        try:
            return self._inner.arrow_c_stream(requested_schema)
        except Exception as error:
            raise translate(error) from None


class Series(SeriesMixin):
    """A one dimensional labelled array holding data of a single type."""

    __slots__ = ()

    @classmethod
    def _wrap(cls, inner: _firepanda.Series) -> Series:
        """Puts the wrapper around an extension object.

        Not a public entry point. It allocates without going through
        __init__ because __init__ is the pandas constructor, which takes
        data rather than an extension object.
        """
        self = object.__new__(cls)
        self._inner = inner
        return self

    def __len__(self) -> int:
        """The number of rows, so that len(s) works."""
        try:
            return self._inner.length()
        except Exception as error:
            raise translate(error) from None

    def __repr__(self) -> str:
        """The series, rendered."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    def __str__(self) -> str:
        """The series, rendered. Same as repr, which is what pandas does."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    @property
    def name(self) -> str:
        """The name of the series."""
        try:
            return self._inner.label()
        except Exception as error:
            raise translate(error) from None

    @property
    def dtype(self) -> str:
        """The type of the values, as a string rather than a numpy dtype."""
        try:
            return self._inner.dtype()
        except Exception as error:
            raise translate(error) from None

    @property
    def size(self) -> int:
        """The number of elements."""
        try:
            return self._inner.length()
        except Exception as error:
            raise translate(error) from None

    @property
    def shape(self) -> tuple[int]:
        """A tuple of the number of rows, which for a series is one long."""
        try:
            return (self._inner.length(),)
        except Exception as error:
            raise translate(error) from None

    @property
    def index(self) -> Index:
        """The row labels of the series."""
        try:
            return Index._wrap(self._inner.labels())
        except Exception as error:
            raise translate(error) from None

    def head(self, n: int = 5) -> Series:
        """The first n rows."""
        try:
            return Series._wrap(self._inner.head(n))
        except Exception as error:
            raise translate(error) from None

    def tail(self, n: int = 5) -> Series:
        """The last n rows."""
        try:
            return Series._wrap(self._inner.tail(n))
        except Exception as error:
            raise translate(error) from None

    def tolist(self) -> list[object]:
        """The values as a Python list, with None where a value is missing."""
        try:
            return list(self._inner.to_list())
        except Exception as error:
            raise translate(error) from None

    def count(self) -> int:
        """The number of values that are not missing."""
        try:
            return self._inner.length() - self._inner.null_count()
        except Exception as error:
            raise translate(error) from None

    @property
    def hasnans(self) -> bool:
        """Whether any value is missing."""
        try:
            return self._inner.null_count() > 0
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_schema__(self) -> object:
        """The column's Arrow schema, as an arrow_schema PyCapsule."""
        try:
            return self._inner.arrow_c_schema()
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, ...]:
        """The column's Arrow data, as an arrow_schema and an arrow_array PyCapsule."""
        try:
            return tuple(self._inner.arrow_c_array(requested_schema))
        except Exception as error:
            raise translate(error) from None


class Index(IndexMixin):
    """The labels of the rows, which is what pandas addresses a row by."""

    __slots__ = ()

    @classmethod
    def _wrap(cls, inner: _firepanda.Index) -> Index:
        """Puts the wrapper around an extension object.

        Not a public entry point. It allocates without going through
        __init__ because __init__ is the pandas constructor, which takes
        data rather than an extension object.
        """
        self = object.__new__(cls)
        self._inner = inner
        return self

    def __len__(self) -> int:
        """The number of labels, so that len(index) works."""
        try:
            return self._inner.length()
        except Exception as error:
            raise translate(error) from None

    def __repr__(self) -> str:
        """The index, rendered."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    def __str__(self) -> str:
        """The index, rendered. Same as repr, which is what pandas does."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    @property
    def name(self) -> str | None:
        """The name of the level, or None when it does not have one."""
        try:
            return self._inner.label()
        except Exception as error:
            raise translate(error) from None

    @property
    def dtype(self) -> str:
        """The type of the labels, as a string rather than a numpy dtype."""
        try:
            return self._inner.dtype()
        except Exception as error:
            raise translate(error) from None

    @property
    def inferred_type(self) -> str:
        """What pandas calls the kind of the labels, such as integer or string."""
        try:
            return self._inner.inferred_type()
        except Exception as error:
            raise translate(error) from None

    @property
    def size(self) -> int:
        """The number of labels."""
        try:
            return self._inner.length()
        except Exception as error:
            raise translate(error) from None

    @property
    def shape(self) -> tuple[int]:
        """A tuple of the number of labels, which for a flat index is one long."""
        try:
            return (self._inner.length(),)
        except Exception as error:
            raise translate(error) from None

    @property
    def ndim(self) -> int:
        """The number of dimensions, which is one for every index that is not a MultiIndex."""
        try:
            return 1
        except Exception as error:
            raise translate(error) from None

    @property
    def nlevels(self) -> int:
        """The number of levels, which is one until MultiIndex exists."""
        try:
            return 1
        except Exception as error:
            raise translate(error) from None

    @property
    def empty(self) -> bool:
        """Whether the index has no labels at all."""
        try:
            return self._inner.length() == 0
        except Exception as error:
            raise translate(error) from None

    @property
    def nbytes(self) -> int:
        """The bytes the labels occupy, which is zero for a range that stores none."""
        try:
            return self._inner.nbytes()
        except Exception as error:
            raise translate(error) from None

    @property
    def hasnans(self) -> bool:
        """Whether any label is missing."""
        try:
            return self._inner.null_count() > 0
        except Exception as error:
            raise translate(error) from None

    @property
    def values(self) -> list[object]:
        """The labels as a Python list, where pandas hands back a numpy array."""
        try:
            return list(self._inner.to_list())
        except Exception as error:
            raise translate(error) from None

    @property
    def is_unique(self) -> bool:
        """Whether every label appears exactly once."""
        try:
            return self._inner.is_unique()
        except Exception as error:
            raise translate(error) from None

    @property
    def has_duplicates(self) -> bool:
        """Whether any label appears more than once."""
        try:
            return not self._inner.is_unique()
        except Exception as error:
            raise translate(error) from None

    @property
    def is_monotonic_increasing(self) -> bool:
        """Whether the labels never decrease, which is False if any is missing."""
        try:
            return self._inner.is_monotonic_increasing()
        except Exception as error:
            raise translate(error) from None

    @property
    def is_monotonic_decreasing(self) -> bool:
        """Whether the labels never increase, which is False if any is missing."""
        try:
            return self._inner.is_monotonic_decreasing()
        except Exception as error:
            raise translate(error) from None

    def tolist(self) -> list[object]:
        """The labels as a Python list, with None where a label is missing."""
        try:
            return list(self._inner.to_list())
        except Exception as error:
            raise translate(error) from None

    def to_list(self) -> list[object]:
        """The labels as a Python list. The pandas spelling with an underscore."""
        try:
            return list(self._inner.to_list())
        except Exception as error:
            raise translate(error) from None

    def unique(self) -> Index:
        """The index with each label kept once, in first seen order."""
        try:
            return Index._wrap(self._inner.unique())
        except Exception as error:
            raise translate(error) from None

    def rename(self, name: str | None) -> Index:
        """The index under a different level name."""
        try:
            return Index._wrap(self._inner.renamed(name))
        except Exception as error:
            raise translate(error) from None

    def take(self, indices: Sequence[int]) -> Index:
        """The labels at a set of positions, in the order given."""
        try:
            return Index._wrap(self._inner.take(list(indices)))
        except Exception as error:
            raise translate(error) from None

    def insert(self, loc: int, item: object) -> Index:
        """The index with one label put in at a position."""
        try:
            return Index._wrap(self._inner.insert(loc, item))
        except Exception as error:
            raise translate(error) from None

    def get_slice_bound(self, label: object, side: str) -> int:
        """The position a label maps to when the index is read in order."""
        try:
            return self._inner.get_slice_bound(label, side)
        except Exception as error:
            raise translate(error) from None

    def slice_locs(self, start: object = None, end: object = None) -> tuple[int, ...]:
        """The half open row range a pair of labels describes, both ends inclusive."""
        try:
            return tuple(self._inner.slice_locs(start, end))
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_schema__(self) -> object:
        """The labels' Arrow schema, as an arrow_schema PyCapsule."""
        try:
            return self._inner.arrow_c_schema()
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, ...]:
        """The labels' Arrow data, as an arrow_schema and an arrow_array PyCapsule."""
        try:
            return tuple(self._inner.arrow_c_array(requested_schema))
        except Exception as error:
            raise translate(error) from None


def read_csv(filepath_or_buffer: str) -> DataFrame:
    """Reads a CSV file into a frame."""
    try:
        return DataFrame._wrap(_firepanda.read_csv(filepath_or_buffer))
    except Exception as error:
        raise translate(error) from None


def from_arrow(source: object) -> DataFrame:
    """Builds a frame from a pyarrow, Polars or pandas frame."""
    try:
        return DataFrame._wrap(_firepanda.from_arrow(source))
    except Exception as error:
        raise translate(error) from None


def _raise_for_test(kind: str) -> object:
    """Raises one classified error of the given kind. For tests only."""
    try:
        return _firepanda._raise_for_test(kind)
    except Exception as error:
        raise translate(error) from None
