# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""The pandas surface.

Every class here holds an extension object and delegates to it. The reason
it is not the extension object itself is document 13: a bound Mojo type
cannot carry a property, an operator or a dunder, cannot be subclassed and
has no __dict__, so 28 percent of pandas is unreachable from there.
"""

from __future__ import annotations

from . import _firepanda

__all__ = ["DataFrame"]


class DataFrame:
    """A two dimensional labelled data structure with columns of potentially different
    types.
    """

    __slots__ = ("_inner",)

    def __init__(self, inner: _firepanda.DataFrame) -> None:
        """Wraps an extension object. Not a public entry point."""
        self._inner = inner

    def __len__(self) -> int:
        """The number of rows, so that len(df) works."""
        return self._inner.length()

    def __repr__(self) -> str:
        """The frame, rendered."""
        return repr(self._inner)

    def __str__(self) -> str:
        """The frame, rendered. Same as repr, which is what pandas does."""
        return repr(self._inner)

    @property
    def columns(self) -> list[str]:
        """The column labels of the frame."""
        return self._inner.names()

    @property
    def shape(self) -> tuple[int, int]:
        """A tuple of the number of rows and the number of columns."""
        return (self._inner.length(), self._inner.width())

    def head(self, n: int = 5) -> DataFrame:
        """The first n rows."""
        return DataFrame(self._inner.head(n))

    def tail(self, n: int = 5) -> DataFrame:
        """The last n rows."""
        return DataFrame(self._inner.tail(n))


def read_csv(filepath_or_buffer: str) -> DataFrame:
    """Reads a CSV file into a frame."""
    return DataFrame(_firepanda.read_csv(filepath_or_buffer))
