# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""The pandas surface.

Every class here holds an extension object and delegates to it. The reason
it is not the extension object itself is document 13: a bound Mojo type
cannot carry a property, an operator or a dunder, cannot be subclassed and
has no __dict__, so 28 percent of pandas is unreachable from there.

Every delegation is wrapped, because a Mojo error arrives as a bare
Exception and `errors.translate` is what puts the class back. The try costs
nothing when nothing raises, which is measured in document 14.
"""

from __future__ import annotations

from . import _firepanda
from ._pandas import DataFrameMixin, SeriesMixin
from .errors import translate

__all__ = ["DataFrame", "Series"]


class DataFrame(DataFrameMixin):
    """A two dimensional labelled data structure with columns of potentially different
    types.
    """

    __slots__ = ()

    @classmethod
    def _wrap(cls, inner: _firepanda.DataFrame) -> DataFrame:
        """Puts the wrapper around an extension object.

        Not a public entry point. It allocates without going through
        __init__ because __init__ is the pandas constructor, which takes
        data rather than an extension object.
        """
        self = object.__new__(cls)
        self._inner = inner
        return self

    def __len__(self) -> int:
        """The number of rows, so that len(df) works."""
        try:
            return self._inner.length()
        except Exception as error:
            raise translate(error) from None

    def __repr__(self) -> str:
        """The frame, rendered."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    def __str__(self) -> str:
        """The frame, rendered. Same as repr, which is what pandas does."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    @property
    def columns(self) -> list[str]:
        """The column labels of the frame."""
        try:
            return self._inner.names()
        except Exception as error:
            raise translate(error) from None

    @property
    def shape(self) -> tuple[int, int]:
        """A tuple of the number of rows and the number of columns."""
        try:
            return (self._inner.length(), self._inner.width())
        except Exception as error:
            raise translate(error) from None

    def head(self, n: int = 5) -> DataFrame:
        """The first n rows."""
        try:
            return DataFrame._wrap(self._inner.head(n))
        except Exception as error:
            raise translate(error) from None

    def tail(self, n: int = 5) -> DataFrame:
        """The last n rows."""
        try:
            return DataFrame._wrap(self._inner.tail(n))
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_schema__(self) -> object:
        """The frame's Arrow schema, as an arrow_schema PyCapsule."""
        try:
            return self._inner.arrow_c_schema()
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, ...]:
        """The frame's Arrow data, as an arrow_schema and an arrow_array PyCapsule."""
        try:
            return tuple(self._inner.arrow_c_array(requested_schema))
        except Exception as error:
            raise translate(error) from None


class Series(SeriesMixin):
    """A one dimensional labelled array holding data of a single type."""

    __slots__ = ()

    @classmethod
    def _wrap(cls, inner: _firepanda.Series) -> Series:
        """Puts the wrapper around an extension object.

        Not a public entry point. It allocates without going through
        __init__ because __init__ is the pandas constructor, which takes
        data rather than an extension object.
        """
        self = object.__new__(cls)
        self._inner = inner
        return self

    def __len__(self) -> int:
        """The number of rows, so that len(s) works."""
        try:
            return self._inner.length()
        except Exception as error:
            raise translate(error) from None

    def __repr__(self) -> str:
        """The series, rendered."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    def __str__(self) -> str:
        """The series, rendered. Same as repr, which is what pandas does."""
        try:
            return repr(self._inner)
        except Exception as error:
            raise translate(error) from None

    @property
    def name(self) -> str:
        """The name of the series."""
        try:
            return self._inner.label()
        except Exception as error:
            raise translate(error) from None

    @property
    def dtype(self) -> str:
        """The type of the values, as a string rather than a numpy dtype."""
        try:
            return self._inner.dtype()
        except Exception as error:
            raise translate(error) from None

    @property
    def size(self) -> int:
        """The number of elements."""
        try:
            return self._inner.length()
        except Exception as error:
            raise translate(error) from None

    @property
    def shape(self) -> tuple[int]:
        """A tuple of the number of rows, which for a series is one long."""
        try:
            return (self._inner.length(),)
        except Exception as error:
            raise translate(error) from None

    def head(self, n: int = 5) -> Series:
        """The first n rows."""
        try:
            return Series._wrap(self._inner.head(n))
        except Exception as error:
            raise translate(error) from None

    def tail(self, n: int = 5) -> Series:
        """The last n rows."""
        try:
            return Series._wrap(self._inner.tail(n))
        except Exception as error:
            raise translate(error) from None

    def tolist(self) -> list[object]:
        """The values as a Python list, with None where a value is missing."""
        try:
            return list(self._inner.to_list())
        except Exception as error:
            raise translate(error) from None

    def count(self) -> int:
        """The number of values that are not missing."""
        try:
            return self._inner.length() - self._inner.null_count()
        except Exception as error:
            raise translate(error) from None

    @property
    def hasnans(self) -> bool:
        """Whether any value is missing."""
        try:
            return self._inner.null_count() > 0
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_schema__(self) -> object:
        """The column's Arrow schema, as an arrow_schema PyCapsule."""
        try:
            return self._inner.arrow_c_schema()
        except Exception as error:
            raise translate(error) from None

    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, ...]:
        """The column's Arrow data, as an arrow_schema and an arrow_array PyCapsule."""
        try:
            return tuple(self._inner.arrow_c_array(requested_schema))
        except Exception as error:
            raise translate(error) from None


def read_csv(filepath_or_buffer: str) -> DataFrame:
    """Reads a CSV file into a frame."""
    try:
        return DataFrame._wrap(_firepanda.read_csv(filepath_or_buffer))
    except Exception as error:
        raise translate(error) from None


def from_arrow(source: object) -> DataFrame:
    """Builds a frame from a pyarrow, Polars or pandas frame."""
    try:
        return DataFrame._wrap(_firepanda.from_arrow(source))
    except Exception as error:
        raise translate(error) from None


def _raise_for_test(kind: str) -> object:
    """Raises one classified error of the given kind. For tests only."""
    try:
        return _firepanda._raise_for_test(kind)
    except Exception as error:
        raise translate(error) from None
