"""`to_latex` against the text pandas writes, recorded because pandas needs jinja2 to write it."""

from __future__ import annotations

import io
from collections.abc import Callable
from typing import Any

import pytest

import firepanda as fp


def frame() -> Any:
    return fp.DataFrame({"a": [1, 2], "b": [1.5, None], "c": ["x_y", "z&w"]})


CASES: dict[str, tuple[Callable[[], Any], tuple[str, ...]]] = {
    "basic": (
        lambda: frame().to_latex(),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "noindex": (
        lambda: frame().to_latex(index=False),
        (
            "\\begin{tabular}{rrl}",
            "\\toprule",
            "a & b & c \\\\",
            "\\midrule",
            "1 & 1.500000 & x_y \\\\",
            "2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "noheader": (
        lambda: frame().to_latex(header=False),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "header-list": (
        lambda: frame().to_latex(header=["A", "B", "C"]),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & A & B & C \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "colfmt": (
        lambda: frame().to_latex(column_format="lcr|l"),
        (
            "\\begin{tabular}{lcr|l}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "float": (
        lambda: frame().to_latex(float_format="%.2f"),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.50 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "float-fn": (
        lambda: frame().to_latex(float_format=lambda v: f"{v:.3f}"),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "na": (
        lambda: frame().to_latex(na_rep="--"),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & -- & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "escape": (
        lambda: frame().to_latex(escape=True),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x\\_y \\\\",
            "1 & 2 & NaN & z\\&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "caption": (
        lambda: frame().to_latex(caption="Cap", label="tab:x"),
        (
            "\\begin{table}",
            "\\caption{Cap}",
            "\\label{tab:x}",
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ),
    ),
    "caption-pair": (
        lambda: frame().to_latex(caption=("Long", "Short")),
        (
            "\\begin{table}",
            "\\caption[Short]{Long}",
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ),
    ),
    "position": (
        lambda: frame().to_latex(caption="Cap", position="h"),
        (
            "\\begin{table}[h]",
            "\\caption{Cap}",
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ),
    ),
    "longtable": (
        lambda: frame().to_latex(longtable=True),
        (
            "\\begin{longtable}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endfirsthead",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endhead",
            "\\midrule",
            "\\multicolumn{4}{r}{Continued on next page} \\\\",
            "\\midrule",
            "\\endfoot",
            "\\bottomrule",
            "\\endlastfoot",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\end{longtable}",
            "",
        ),
    ),
    "longtable-cap": (
        lambda: frame().to_latex(longtable=True, caption="C", label="L"),
        (
            "\\begin{longtable}{lrrl}",
            "\\caption{C} \\label{L} \\\\",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endfirsthead",
            "\\caption[]{C} \\\\",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endhead",
            "\\midrule",
            "\\multicolumn{4}{r}{Continued on next page} \\\\",
            "\\midrule",
            "\\endfoot",
            "\\bottomrule",
            "\\endlastfoot",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\end{longtable}",
            "",
        ),
    ),
    "bold": (
        lambda: frame().to_latex(bold_rows=True),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\textbf{0} & 1 & 1.500000 & x_y \\\\",
            "\\textbf{1} & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "columns": (
        lambda: frame().to_latex(columns=["a", "c"]),
        (
            "\\begin{tabular}{lrl}",
            "\\toprule",
            " & a & c \\\\",
            "\\midrule",
            "0 & 1 & x_y \\\\",
            "1 & 2 & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "series": (
        lambda: fp.Series([1, 2], name="s").to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & s \\\\",
            "\\midrule",
            "0 & 1 \\\\",
            "1 & 2 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "series-noname": (
        lambda: fp.Series([1.25, 2.5]).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & 0 \\\\",
            "\\midrule",
            "0 & 1.250000 \\\\",
            "1 & 2.500000 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "named-index": (
        lambda: fp.DataFrame({"a": [1]}, index=fp.Index(["r"], name="key")).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a \\\\",
            "key &  \\\\",
            "\\midrule",
            "r & 1 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "bools": (
        lambda: fp.DataFrame({"a": [True, False]}).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0 & True \\\\",
            "1 & False \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "dates": (
        lambda: fp.DataFrame({"a": fp.to_datetime(["2026-01-01"])}).to_latex(),
        (
            "\\begin{tabular}{ll}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0 & 2026-01-01 00:00:00 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "empty": (
        lambda: fp.DataFrame().to_latex(),
        ("\\begin{tabular}{l}", "\\toprule", "\\midrule", "\\bottomrule", "\\end{tabular}", ""),
    ),
    "empty-cols": (
        lambda: fp.DataFrame({"a": []}).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "buf": (lambda: frame().to_latex(buf=None) == frame().to_latex(), ("True",)),
    "formatters": (
        lambda: frame().to_latex(formatters={"a": lambda v: f"<{v}>"}),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & <1> & 1.500000 & x_y \\\\",
            "1 & <2> & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "formatters-list": (
        lambda: frame().to_latex(formatters=[str, str, str]),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.5 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "decimal": (
        lambda: frame().to_latex(decimal=","),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1,500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "sparsify": (
        lambda: frame().to_latex(sparsify=False),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "big": (
        lambda: fp.DataFrame({"a": [1234567.891]}).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0 & 1234567.891000 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "neg": (
        lambda: fp.DataFrame({"a": [-1, 2]}).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0 & -1 \\\\",
            "1 & 2 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "mixed-float": (
        lambda: fp.DataFrame({"a": [1.0, 2.123456789]}).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0 & 1.000000 \\\\",
            "1 & 2.123457 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "int-names": (
        lambda: fp.DataFrame({0: [1], 1: [2]}).to_latex(),
        (
            "\\begin{tabular}{lrr}",
            "\\toprule",
            " & 0 & 1 \\\\",
            "\\midrule",
            "0 & 1 & 2 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "escape-cols": (
        lambda: fp.DataFrame({"a_b": [1]}).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a_b \\\\",
            "\\midrule",
            "0 & 1 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "escape-off": (
        lambda: fp.DataFrame({"a_b": ["%"]}).to_latex(escape=False),
        (
            "\\begin{tabular}{ll}",
            "\\toprule",
            " & a_b \\\\",
            "\\midrule",
            "0 & % \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "multicol": (
        lambda: frame().to_latex(multicolumn=False, multirow=False, multicolumn_format="c"),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "encoding": (
        lambda: frame().to_latex(encoding="utf-8"),
        ("ValueError: buf is not a file name and encoding is specified.",),
    ),
    "index_names": (
        lambda: fp.DataFrame({"a": [1]}, index=fp.Index(["r"], name="key")).to_latex(
            index_names=False
        ),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "r & 1 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "lt-pos": (
        lambda: frame().to_latex(longtable=True, position="h"),
        (
            "\\begin{longtable}[h]{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endfirsthead",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endhead",
            "\\midrule",
            "\\multicolumn{4}{r}{Continued on next page} \\\\",
            "\\midrule",
            "\\endfoot",
            "\\bottomrule",
            "\\endlastfoot",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\end{longtable}",
            "",
        ),
    ),
    "lt-label": (
        lambda: frame().to_latex(longtable=True, label="L"),
        (
            "\\begin{longtable}{lrrl}",
            "\\label{L} \\\\",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endfirsthead",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endhead",
            "\\midrule",
            "\\multicolumn{4}{r}{Continued on next page} \\\\",
            "\\midrule",
            "\\endfoot",
            "\\bottomrule",
            "\\endlastfoot",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\end{longtable}",
            "",
        ),
    ),
    "lt-pair": (
        lambda: frame().to_latex(longtable=True, caption=("Long", "Short")),
        (
            "\\begin{longtable}{lrrl}",
            "\\caption[Short]{Long} \\\\",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endfirsthead",
            "\\caption[]{Long} \\\\",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endhead",
            "\\midrule",
            "\\multicolumn{4}{r}{Continued on next page} \\\\",
            "\\midrule",
            "\\endfoot",
            "\\bottomrule",
            "\\endlastfoot",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\end{longtable}",
            "",
        ),
    ),
    "label-only": (
        lambda: frame().to_latex(label="L"),
        (
            "\\begin{table}",
            "\\label{L}",
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.500000 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ),
    ),
    "esc-labels": (
        lambda: fp.DataFrame({"a_b": ["&"]}, index=fp.Index(["x%"], name="k_1")).to_latex(
            escape=True
        ),
        (
            "\\begin{tabular}{ll}",
            "\\toprule",
            " & a\\_b \\\\",
            "k\\_1 &  \\\\",
            "\\midrule",
            "x\\% & \\& \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "noheader-named": (
        lambda: fp.DataFrame({"a": [1]}, index=fp.Index(["r"], name="key")).to_latex(header=False),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            "key &  \\\\",
            "\\midrule",
            "r & 1 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "noindex-named": (
        lambda: fp.DataFrame({"a": [1]}, index=fp.Index(["r"], name="key")).to_latex(index=False),
        (
            "\\begin{tabular}{r}",
            "\\toprule",
            "a \\\\",
            "\\midrule",
            "1 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "float-index": (
        lambda: fp.DataFrame({"a": [1]}, index=[0.5]).to_latex(),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0.500000 & 1 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "str-none": (
        lambda: fp.DataFrame({"a": ["x", None]}).to_latex(),
        (
            "\\begin{tabular}{ll}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0 & x \\\\",
            "1 & NaN \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "header-bad": (
        lambda: frame().to_latex(header=["A"]),
        ("ValueError: Writing 3 cols but got 1 aliases",),
    ),
    "escape-special": (
        lambda: fp.DataFrame({"a": ["~ ^ \\ {x} $#"]}).to_latex(escape=True),
        (
            "\\begin{tabular}{ll}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0 & \\textasciitilde \\space \\textasciicircum \\space "
            "\\textbackslash \\space \\{x\\} \\$\\# \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "series-float-fmt": (
        lambda: fp.Series([1.5], name="v").to_latex(float_format="%.1f"),
        (
            "\\begin{tabular}{lr}",
            "\\toprule",
            " & v \\\\",
            "\\midrule",
            "0 & 1.5 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "bold-lt": (
        lambda: frame().to_latex(bold_rows=True, longtable=True),
        (
            "\\begin{longtable}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endfirsthead",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "\\endhead",
            "\\midrule",
            "\\multicolumn{4}{r}{Continued on next page} \\\\",
            "\\midrule",
            "\\endfoot",
            "\\bottomrule",
            "\\endlastfoot",
            "\\textbf{0} & 1 & 1.500000 & x_y \\\\",
            "\\textbf{1} & 2 & NaN & z&w \\\\",
            "\\end{longtable}",
            "",
        ),
    ),
    "fmt-and-float": (
        lambda: frame().to_latex(formatters={"a": str}, float_format="%.1f"),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & 1 & 1.5 & x_y \\\\",
            "1 & 2 & NaN & z&w \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "list-and-float": (
        lambda: frame().to_latex(
            formatters=[lambda v: "i", lambda v: "f", lambda v: "s"], float_format="%.1f"
        ),
        (
            "\\begin{tabular}{lrrl}",
            "\\toprule",
            " & a & b & c \\\\",
            "\\midrule",
            "0 & i & 1.5 & s \\\\",
            "1 & i & NaN & s \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
    "timedelta": (
        lambda: fp.DataFrame({"a": fp.to_timedelta(["1 day"])}).to_latex(),
        (
            "\\begin{tabular}{ll}",
            "\\toprule",
            " & a \\\\",
            "\\midrule",
            "0 & 1 days 00:00:00 \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "",
        ),
    ),
}


def outcome(case: Callable[[], Any]) -> str:
    try:
        found = case()
    except Exception as mistake:
        kind = next(c.__name__ for c in type(mistake).__mro__ if c.__module__ == "builtins")
        return f"{kind}: {mistake}"
    return found if isinstance(found, str) else repr(found)


@pytest.mark.parametrize("name", list(CASES))
def test_writes_what_pandas_writes(name: str) -> None:
    case, expected = CASES[name]
    assert outcome(case) == "\n".join(expected)


def test_a_buffer_gets_the_text_and_nothing_comes_back() -> None:
    buf = io.StringIO()
    assert frame().to_latex(buf) is None
    assert buf.getvalue() == frame().to_latex()


def test_a_path_gets_the_text(tmp_path: Any) -> None:
    path = tmp_path / "table.tex"
    frame().to_latex(path)
    assert path.read_text() == frame().to_latex()
