"""Writes the table of code points where this library's case data is not pandas'.

pandas 3 holds a text column in Arrow and its `str.upper` and `str.lower` are Arrow
compute kernels, which use the simple case mappings and never make a row longer. The
Mojo standard library carries its own case data, which is mostly the same table and
differs in two ways: it applies the full mappings for a few dozen code points, so `ss`
comes out where Arrow gives one letter, and it does not know a few code points that
were added to Unicode after its copy was made.

This script measures the difference by walking every code point through both sides and
writes the ones that disagree into a Mojo source file, which `chars.mojo` uses to
correct its answers. It needs pyarrow, so it is not run by CI, and the generated file
is committed. Run it when either side moves:

    uv run --no-project --python 3.13 --with pyarrow python tools/gen_casefix.py

It reads the standard library's side from a file produced by a Mojo probe rather than
by calling Mojo itself, because there is no way to call a Mojo function from Python
here. The probe is printed by --probe and its output is passed with --mojo.

It also checks two rules the kernels rely on and refuses to write anything if either
one stops holding: that `swapcase` is decidable from the mappings plus a short list of
titlecase characters, and that `capitalize` is the first character raised and the rest
dropped. Both are measured against Arrow over every code point rather than trusted.
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

PROBE = """from std.collections.string import Codepoint


def codes(s: StringSlice) -> String:
    var out = String()
    for c in s.codepoints():
        if out:
            out += "."
        out += hex(Int(c.to_u32()))
    return out^


def main():
    var maps = String()
    for cp in range(0, 0x110000):
        if cp >= 0xD800 and cp <= 0xDFFF:
            continue
        var one = String(Codepoint(unsafe_unchecked_codepoint=UInt32(cp)))
        var up = one.upper()
        var lo = one.lower()
        if up != one or lo != one:
            maps += String(hex(cp), ":", codes(up), ":", codes(lo), " ")
    print("MAPS", maps)
"""

HEADER = '''"""Where this library\'s case data is not the case data pandas answers out of.

pandas 3 holds a text column in Arrow, and `str.upper` and `str.lower` on such a
column are Arrow compute kernels rather than Python\'s own string methods. Arrow
uses the simple case mappings, which are one code point in and one code point
out, so a row that goes in eight characters long comes out eight characters long
whatever is in it. Python uses the full mappings, where a sharp s raises to two
letters, and the two answers are different for {count} code points out of the
million or so there are. Document 64 measures the whole difference.

The Mojo standard library agrees with Arrow almost everywhere and differs in two
ways. It applies the full mapping for {expanding} code points, which is Python\'s
answer rather than Arrow\'s. And it does not know {added} code points that were
added to Unicode after its copy of the data was made, so it leaves them alone
where Arrow changes their case.

This file is the list of both, with what Arrow answers for each. `chars.mojo`
checks an element for any of these before it hands it to the standard library,
and builds the answer a code point at a time when it finds one, which is the
only path in that file that is slower than one call per element. Nothing here
is reachable from ASCII text.

The first three tables are one list of code points and two lists of answers, in
the same order, so that one piece of code can hold either direction. A code
point that only disagrees in one direction still has an entry in both, and the
entry for the direction that agrees is the answer both sides already give.

The fourth table is a different list for a different kernel. `swapcase` asks
which case a character is in before it changes it, and the answer for the {kept}
titlecase characters is neither, so Arrow leaves them exactly as they are even
though both of their mappings would move them. Every other character can be
classified by its mappings alone, since one that lowers to something else was
upper and one that raises to something else was lower, so this list is the whole
of what the mappings cannot say and `swapcase` needs no case data beyond it.

Generated by tools/gen_casefix.py against pyarrow {pyarrow}. It is committed
rather than built, because the generator needs pyarrow and the Mojo build does
not have it. The Python tests assert several of these rows against a running
pandas, so a change on either side fails a test rather than passing quietly.
"""

'''


def mojo_maps(path: Path) -> dict[int, tuple[str, str]]:
    """Reads the probe output, which is one line naming every mapped code point."""
    text = path.read_text()
    line = next(line for line in text.splitlines() if line.startswith("MAPS "))
    out: dict[int, tuple[str, str]] = {}
    for item in line[len("MAPS ") :].split():
        cp, up, lo = item.split(":")
        out[int(cp, 16)] = (
            "".join(chr(int(c, 16)) for c in up.split(".")),
            "".join(chr(int(c, 16)) for c in lo.split(".")),
        )
    return out


def table(name: str, values: list[int]) -> str:
    """One comptime array, a code point to a line.

    A line each rather than a row of eight because that is the shape the Mojo
    formatter puts a long literal in, and a generator whose output the formatter
    rewrites is a generator nobody can tell has been run.
    """
    body = "\n".join(f"    0x{v:04X}," for v in values)
    return f"comptime {name}: InlineArray[UInt32, {len(values)}] = [\n{body}\n]\n"


def check_swapcase(points, chars, swapped, up_of, lo_of, kept) -> None:
    """Asserts that the mappings plus the kept list are all `swapcase` needs.

    The rule the kernel uses is written out here against every code point there
    is, because the whole claim of the kept list is that nothing else has to be
    known. A character in the list is left alone, one that lowers to something
    else was upper and goes down, one that raises to something else was lower
    and goes up, and anything the mappings do not move is not cased. If that
    ever stops being the whole story this raises rather than writing a table
    the kernel would quietly be wrong about.
    """
    for cp, ch, want in zip(points, chars, swapped, strict=True):
        if cp in kept:
            got = ch
        elif lo_of[cp] != ch:
            got = lo_of[cp]
        elif up_of[cp] != ch:
            got = up_of[cp]
        else:
            got = ch
        if got != want:
            raise SystemExit(f"swapcase rule is wrong for {cp:04X}: {got!r} not {want!r}")


def check_capitalize(pa, pc, points, chars, up_of, lo_of) -> None:
    """Asserts that capitalize is the first character raised and the rest dropped.

    Arrow documents it that way and this measures it, over every code point on
    its own and then over a few thousand words built out of the range where the
    cased characters live, because the part worth checking is not the first
    character but whether the rest really is a plain lowering.
    """
    for cp, want in zip(points, pc.utf8_capitalize(pa.array(chars)).to_pylist(), strict=True):
        if up_of[cp] != want:
            raise SystemExit(f"capitalize is not upper for {cp:04X}")
    rng = random.Random(0)
    cased = [c for c in points if up_of[c] != chr(c) or lo_of[c] != chr(c)]
    words = ["".join(chr(rng.choice(cased)) for _ in range(6)) for _ in range(4000)]
    for word, want in zip(words, pc.utf8_capitalize(pa.array(words)).to_pylist(), strict=True):
        got = up_of[ord(word[0])] + "".join(lo_of[ord(c)] for c in word[1:])
        if got != want:
            raise SystemExit(f"capitalize rule is wrong for {word!r}: {got!r} not {want!r}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--probe", action="store_true", help="print the Mojo probe")
    parser.add_argument("--mojo", type=Path, help="the probe's output")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("firepanda/kernel/casefix.mojo"),
        help="where to write the table",
    )
    args = parser.parse_args()

    if args.probe:
        sys.stdout.write(PROBE)
        return 0
    if args.mojo is None:
        parser.error("--mojo is required unless --probe is given")

    import pyarrow as pa
    import pyarrow.compute as pc

    theirs = mojo_maps(args.mojo)
    points = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]
    chars = [chr(c) for c in points]
    arrow = pa.array(chars)
    raised = pc.utf8_upper(arrow).to_pylist()
    dropped = pc.utf8_lower(arrow).to_pylist()

    keys: list[int] = []
    ups: list[int] = []
    downs: list[int] = []
    expanding = 0
    added = 0
    for cp, ch, up, lo in zip(points, chars, raised, dropped, strict=True):
        mine_up, mine_lo = theirs.get(cp, (ch, ch))
        if up == mine_up and lo == mine_lo:
            continue
        if len(up) != 1 or len(lo) != 1:
            raise SystemExit(f"arrow gave more than one code point for {cp:04X}")
        if len(mine_up) > 1 or len(mine_lo) > 1:
            expanding += 1
        else:
            added += 1
        keys.append(cp)
        ups.append(ord(up))
        downs.append(ord(lo))

    up_of = dict(zip(points, raised, strict=True))
    lo_of = dict(zip(points, dropped, strict=True))
    swapped = pc.utf8_swapcase(arrow).to_pylist()
    kept = [
        cp
        for cp, ch, want in zip(points, chars, swapped, strict=True)
        if want == ch and (up_of[cp] != ch or lo_of[cp] != ch)
    ]
    check_swapcase(points, chars, swapped, up_of, lo_of, set(kept))
    check_capitalize(pa, pc, points, chars, up_of, lo_of)

    lowest = min(keys)
    body = HEADER.format(
        count=len(keys),
        expanding=expanding,
        added=added,
        kept=len(kept),
        pyarrow=pa.__version__,
    )
    body += table("CORRECTED_FROM", keys)
    body += '"""The code points whose case this library gets wrong, in order."""\n\n'
    body += table("CORRECTED_UP", ups)
    body += '"""What Arrow raises each of them to, in the same order."""\n\n'
    body += table("CORRECTED_DOWN", downs)
    body += '"""What Arrow lowers each of them to, in the same order."""\n\n'
    body += table("KEPT_BY_SWAP", kept)
    body += (
        '"""The code points `swapcase` leaves alone despite their mappings.\n\n'
        "These are the titlecase characters. They are in neither case, so there\n"
        "is no other case to write them in, and both of their mappings would\n"
        "move them if the mappings were all a caller had to go on.\n"
        '"""\n\n'
    )
    body += f"comptime LOWEST_CORRECTED_LEAD = Byte(0x{0xC0 | (lowest >> 6):02X})\n"
    body += (
        '"""The first byte of the lowest code point in the table.\n\n'
        "An element with no byte this large in it holds nothing that needs\n"
        "correcting, which is every ASCII element and most others, and that test\n"
        "is one pass over the bytes with no decoding in it.\n"
        '"""\n'
    )
    args.out.write_text(body)
    print(f"{len(keys)} corrections, {expanding} expanding, {added} unknown here")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
