#!/usr/bin/env python3
"""Writes firepanda/sql/generated/functions.mojo from DuckDB's own catalog.

The tier 1 names are listed here and everything else about them is read out of
`duckdb_functions()` on a live DuckDB: the overloads, their parameter types,
their return types and which of them take varargs. Typing the signatures by
hand would mean typing 800 of them, and the ones that would be wrong are the
ones nobody would check, like `sum(BOOLEAN)` returning `HUGEINT` and `min`
having a second overload that gives back a list.

The name list is the tier 1 set from docs/specs/sql/07-functions.md section 4,
plus the aliases DuckDB ships for those names, because a query that says
`substr` is a query that says `substring` and a registry that knows only one of
them refuses a query DuckDB runs.

Three names in the spec's list are not in the catalog at all. `coalesce` and
`ifnull` are grammar rules rather than functions, which is why a wrong argument
count to either one is a parser error and not a binder error, and
`current_timestamp` is a keyword. All three are the transformer's and none of
them belongs here.

Run `pixi run -e differential gen-functions` and commit the result. CI
regenerates it and fails on any diff.

Usage:
    python tools/gen_functions.py            write the table
    python tools/gen_functions.py --check    fail if the checked in file is stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import duckdb

# The tier 1 set, in the order document 07 lists it, with DuckDB's aliases for
# each name folded in beside it. A name that DuckDB spells two ways is two
# entries here, because the catalog carries the overloads under both and the
# candidate list in an error message uses whichever one the query wrote.
TIER_ONE = """
substring substr length len upper ucase lower lcase trim ltrim rtrim
concat concat_ws replace strpos position instr left right lpad rpad
split_part starts_with ends_with contains repeat reverse md5
regexp_matches regexp_replace regexp_extract regexp_full_match
regexp_split_to_array like_escape ilike_escape prefix suffix printf format
string_split str_split split

date_part datepart date_trunc datetrunc date_diff datediff date_add date_sub
strftime strptime age current_date current_localtimestamp now
get_current_timestamp today epoch epoch_ms make_date make_time make_timestamp
last_day monthname dayname to_timestamp century

abs round ceil ceiling floor sign sqrt pow power exp ln log log10 log2
sin cos tan asin acos atan atan2 cot sinh cosh tanh degrees radians pi
greatest least mod even factorial gcd lcm bit_count cbrt

typeof

count sum avg min max stddev stddev_samp stddev_pop variance var_samp var_pop
median quantile quantile_cont quantile_disc approx_quantile
approx_count_distinct string_agg group_concat listagg list array_agg
bool_and bool_or first last any_value arg_min arg_max min_by max_by
sum_no_overflow product corr covar_pop covar_samp entropy kurtosis skewness
mode bit_and bit_or bit_xor histogram

row_number rank dense_rank percent_rank cume_dist ntile lag lead
first_value last_value nth_value
""".split()

# Names the spec asks for that the catalog does not carry, with what they are
# instead. Written down so that the next person to notice one missing finds the
# answer here rather than adding it and watching the generator drop it again.
NOT_FUNCTIONS = {
    "coalesce": "a grammar rule, so a bad argument count is a parser error",
    "ifnull": "a grammar rule, the same as coalesce",
    "current_timestamp": "a keyword, not a call",
}

# A table function and a scalar function can share a name, `repeat` and
# `histogram` being the two in this set, and a call in an expression never
# means the table one. Dropping them here is what keeps a name to one kind.
KINDS = {"scalar": 1, "aggregate": 2, "macro": 3}

# Calls that match nothing, used to check that the overload order written here
# is the order DuckDB lists candidates in. Every overload of a name is on one
# `function_oid`, so ordering the catalog scan by it leaves the order within a
# name to the sort, which is where the first version of this generator went
# wrong and produced a table whose messages were right line by line and in the
# wrong order. The scan without an ORDER BY is already in catalog order, so
# what these probes check is that it stayed that way.
PROBES = [
    "select sum(date '2020-01-01')",
    "select length(1)",
    "select min(1, 2, 3, 4)",
    "select md5(1)",
    "select round(date '2020-01-01')",
    "select trim(1)",
    "select upper(true)",
    "select substr(1)",
]

HEADER = '''"""The tier 1 function catalog, flattened into one table.

Generated by tools/gen_functions.py from DuckDB {version}.
Do not edit. Run `pixi run -e differential gen-functions` and commit the result.

{names} names, {overloads} overloads, {types} distinct types.

The table is one string rather than a list of structs for the same reason
`rules.mojo` is: a literal with hundreds of entries is a compile time cost
paid by everyone who builds firepanda, and the table is read once into a
`Registry`. See docs/specs/sql/07-functions.md section 2.

Every signature is DuckDB's own, read out of `duckdb_functions()` rather
than typed in, including the ones that look wrong. `sum(BOOLEAN)` gives
back a `HUGEINT`, `min` has a second overload taking a count and giving
back a list, and `length` accepts a `BIT`. A registry that was merely
sensible would refuse queries DuckDB runs.
"""


# What a name is. A table function that shares a name with a scalar one is
# not here, because a call in an expression never means the table one.
comptime KIND_SCALAR: UInt8 = 1
comptime KIND_AGGREGATE: UInt8 = 2
comptime KIND_MACRO: UInt8 = 3

# A macro carries no parameter types at all, so it resolves on the count of
# its arguments and nothing else, and its error message is a different
# sentence from the one a function gets.
comptime NO_TYPE: UInt32 = 4294967295

comptime NAME_COUNT: Int = {names}
comptime OVERLOAD_COUNT: Int = {overloads}
comptime TYPE_COUNT: Int = {types}

# The version the table was read off. A signature that changes between
# DuckDB releases changes what firepanda binds, so the number is part of
# the table rather than a note in a commit message.
comptime DUCKDB_VERSION: StaticString = "{version}"

# Three sections, each one line per entry and each in the order the reader
# wants it.
#
# The text section is every distinct type spelling that appears in a
# signature, DuckDB's own words. `ANY` and the single letter names are its
# templates, and a spelling ending in `[]` is a list of the rest. A macro
# carries no types, so its entries here are its parameter names, which is
# what DuckDB shows when it refuses a call to one.
#
# The name section is sorted, so a lookup is a binary search: the name, its
# kind, where its overloads start, how many there are, and the name it is an
# alias of or `-`.
#
# The overload section is in catalog order within each name, because that is
# the order DuckDB lists candidates in when it refuses a call, and a message
# that lists the same signatures in a different order fails the corpus.
# Each line is the kind, the return type, the varargs type or -1, the arity
# and then that many parameter types. A macro writes -1 for every type it
# has, including the return.
comptime TABLE: StaticString = """
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if the output is stale"
    )
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    out = root / "firepanda" / "sql" / "generated" / "functions.mojo"

    connection = duckdb.connect()
    version = connection.execute("select version()").fetchone()[0].lstrip("v")
    # One thread and no ORDER BY, because the scan is already in catalog order
    # and any sort would reorder the overloads within a name, which all share
    # one `function_oid`. PROBES checks the result against DuckDB's own
    # candidate lists.
    connection.execute("set threads = 1")
    rows = connection.execute(
        """
        select function_name, function_type, return_type, parameter_types,
               varargs, alias_of, parameters
        from duckdb_functions()
        where schema_name = 'main'
        """
    ).fetchall()

    wanted = set(TIER_ONE)
    if len(wanted) != len(TIER_ONE):
        seen: set[str] = set()
        twice = sorted({n for n in TIER_ONE if n in seen or seen.add(n)})
        print(f"the name list repeats {twice}", file=sys.stderr)
        return 1

    overloads: dict[str, list[tuple]] = {}
    kinds: dict[str, int] = {}
    aliases: dict[str, str] = {}
    for name, kind, returns, params, varargs, alias, written in rows:
        if name not in wanted or kind not in KINDS:
            continue
        if name in kinds and kinds[name] != KINDS[kind]:
            print(f"{name} is both a {kind} and something else", file=sys.stderr)
            return 1
        kinds[name] = KINDS[kind]
        aliases[name] = alias or "-"
        # A macro has no parameter types, and the candidate line DuckDB prints
        # for one names its parameters instead, so that is what is kept.
        slots = tuple(written or ()) if kind == "macro" else tuple(params or ())
        overloads.setdefault(name, []).append((returns, slots, varargs))

    missing = sorted(wanted - set(overloads))
    unexplained = [n for n in missing if n not in NOT_FUNCTIONS]
    if unexplained:
        print(f"the catalog has no {unexplained}", file=sys.stderr)
        return 1

    def written(
        name: str, returns: str, params: tuple, varargs: str | None
    ) -> str:
        slots = list(params)
        if varargs is not None:
            slots.append(f"[{varargs}...]")
        return f"{name}({', '.join(slots)}) -> {returns}"

    spellings: list[str] = []
    index: dict[str, int] = {}

    def slot(text: str | None) -> int:
        if text is None:
            return -1
        if text not in index:
            index[text] = len(spellings)
            spellings.append(text)
        return index[text]

    # The types first, so the section they are counted in is written before
    # the sections that refer to them.
    lines: list[str] = []
    names = sorted(overloads)
    ordered: list[tuple[str, int, int]] = []
    body: list[str] = []
    for name in names:
        first = len(body)
        for returns, params, varargs in overloads[name]:
            fields = [
                str(kinds[name]),
                str(slot(returns)),
                str(slot(varargs)),
                str(len(params)),
            ]
            fields += [str(slot(p)) for p in params]
            body.append(" ".join(fields))
        ordered.append((name, first, len(body) - first))

    for probe in PROBES:
        try:
            connection.execute(probe)
        except Exception as error:
            said = str(error)
        else:
            print(f"{probe} was supposed to fail", file=sys.stderr)
            return 1
        name = probe.split("select ", 1)[1].split("(", 1)[0]
        listed = [
            line.strip()
            for line in said.split("Candidate functions:\n", 1)[1].split("\n")
            if line.startswith("\t")
        ]
        ours = [
            written(name, returns, params, varargs)
            for returns, params, varargs in overloads[name]
        ]
        if listed != ours:
            print(
                f"the overloads of {name} are out of order:\n"
                f"  duckdb says {listed}\n  this writes {ours}",
                file=sys.stderr,
            )
            return 1

    lines.append(f"F {len(names)} {len(body)} {len(spellings)}")
    lines.extend(spellings)
    for name, first, count in ordered:
        lines.append(f"{name} {kinds[name]} {first} {count} {aliases[name]}")
    lines.extend(body)

    text = HEADER.format(
        version=version,
        names=len(names),
        overloads=len(body),
        types=len(spellings),
    )
    text += "\n".join(lines) + '\n"""\n'
    if args.check:
        if not out.exists():
            print(f"{out.relative_to(root)} does not exist", file=sys.stderr)
            return 1
        if out.read_text() != text:
            print(
                f"{out.relative_to(root)} is stale, run"
                " `pixi run -e differential gen-functions`",
                file=sys.stderr,
            )
            return 1
        print(f"{out.relative_to(root)} is current")
        return 0

    out.write_text(text)
    print(
        f"{out.relative_to(root)}: {len(names)} names, {len(body)} overloads,"
        f" {len(spellings)} types, from DuckDB {version}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
