"""Writes the table of which code points match which when case is ignored.

`(?i)` is one letter in a pattern and two questions underneath. The first is
which code points count as the same letter, and the second is whether the two
engines pandas runs agree about that. The second one had an answer written down
in this repository before it was measured, and the answer written down was
wrong, which is why this generator exists rather than a pair of hand tables.

Both engines are asked here. Python's answer is read out of `_sre` and
`re._casefix`, which is what `re` itself compiles an `(?i)` literal with, and
RE2's answer is read by running pyarrow over every code point that has a case
mapping at all. The two are then compared, and the generator refuses to write
unless the difference is exactly the four code points it expects.

That difference is the whole of it. Python folds `I`, `i`, the dotted capital
`I` and the dotless small `i` into one group of four. RE2 folds `I` and `i`
together and leaves the other two alone, each matching only itself. Every other
one of the 2927 code points either engine considers cased is folded the same way
by both. So this is one table and a four code point exception rather than the
two tables the plan called for.

The candidate set is checked for closure before anything is written. A class
holding every candidate, compiled with `(?i)`, is run against every code point
by both engines, and both have to answer with the candidate set exactly. That is
what rules out a code point neither `str.lower` nor `str.upper` nor
`str.casefold` nor `str.title` moves but some engine still folds.

    uv run --no-project --python 3.13 --with pyarrow python tools/gen_regexfold.py
"""

from __future__ import annotations

import argparse
import re
import sys
import textwrap
import unicodedata
from pathlib import Path

import _sre
from re._casefix import _EXTRA_CASES

HEADER = '''"""Which code points are the same letter when case is ignored.

`(?i)` is settled while a pattern is being compiled and never at run time. A
literal becomes the set of everything that folds onto it, a class has the folds
of everything in it added before the caret is applied, and the machine that runs
the program never learns that a flag was set. That is RE2's arrangement and the
reason for it is that the alternative is a table lookup per character of every
row rather than per character of the pattern.

Both engines pandas runs fold the same way with one exception, which was
measured rather than assumed. Python folds `I`, `i`, the dotted capital `I` at
U+0130 and the dotless small `i` at U+0131 into a single group of four, so
`(?i)i` matches all four. RE2 folds `I` and `i` together and leaves the other two
alone, so `(?i)i` matches two and `(?i)\\u0130` matches only itself. Every other
code point either engine considers cased folds identically in both, which is why
there is one table here and a four code point exception in `program.mojo` rather
than two tables.

The table is the cycle rather than the groups. Each cased code point has one
successor, the next member of its group counting upwards and wrapping round at
the top, so walking the successor from a code point and stopping when it comes
back is the whole group and nothing else. Writing the groups out instead would
be twice the size, because a group of four holds four code points and is written
once for each of them.

The successor is then written as runs, since it is almost always the same
arithmetic over a long stretch of the alphabet. A run is a low, a high and a
delta, and the delta is added to a code point to get its successor. One delta is
not a number: `{even_odd}` means the alphabet alternates upper and lower in
pairs, so an even code point's successor is the one above it and an odd one's is
the one below. That marker is what turns {plain} runs of plain arithmetic into
{runs}, and it is the same encoding Go's `unicode.SimpleFold` uses for the same
reason.

{summary}

Generated by tools/gen_regexfold.py against CPython {python} with Unicode
{unicode} and pyarrow {pyarrow}, committed rather than built because the Mojo
build has no Python in it. The generator checks that the candidate set is closed
under both engines' folding, that the two engines differ on exactly the four
code points above, and that walking these runs reproduces every group it
measured, so a release of either that moves the answer fails there rather than
drifting.
"""

'''

def python_orbits() -> dict[int, tuple[int, ...]]:
    """What `re` matches for an `(?i)` literal, for every cased code point.

    `re` compiles a cased literal down to a comparison of lowered code points,
    so two points are the same letter when `unicode_tolower` sends them to the
    same place. That is not the whole of it: `_casefix` carries fifty groups
    where lowering is not enough, and those link one lowered point to another,
    so the groups have to be merged before they are read.
    """
    groups: dict[int, list[int]] = {}
    for point in range(0x110000):
        if _sre.unicode_iscased(point):
            groups.setdefault(_sre.unicode_tolower(point), []).append(point)

    parent = {key: key for key in groups}

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[max(ra, rb)] = min(ra, rb)

    for lowered, extra in _EXTRA_CASES.items():
        parent.setdefault(lowered, lowered)
        for other in extra if isinstance(extra, (tuple, list)) else (extra,):
            key = _sre.unicode_tolower(other)
            parent.setdefault(key, key)
            union(lowered, key)

    merged: dict[int, list[int]] = {}
    for key, members in groups.items():
        merged.setdefault(find(key), []).extend(members)

    out: dict[int, tuple[int, ...]] = {}
    for members in merged.values():
        group = tuple(sorted(set(members)))
        for point in group:
            out[point] = group
    return out


def re2_orbits(candidates: list[int]) -> dict[int, tuple[int, ...]]:
    """The same question asked of RE2, one pattern per candidate.

    The escape is `\\x{...}` rather than a literal character, so nothing here
    depends on which characters RE2 thinks need escaping. Every row of the array
    is one code point, so a substring match is an equality.
    """
    import pyarrow as pa
    import pyarrow.compute as pc

    array = pa.array([chr(point) for point in candidates], type=pa.string())
    out: dict[int, tuple[int, ...]] = {}
    for point in candidates:
        mask = pc.match_substring_regex(array, r"(?i)\x{%X}" % point).to_pylist()
        out[point] = tuple(
            candidates[i] for i, matched in enumerate(mask) if matched
        )
    return out


def as_class(points: list[int], escape) -> str:
    """The sorted code points written as one character class."""
    runs: list[list[int]] = []
    for point in points:
        if runs and point == runs[-1][1] + 1:
            runs[-1][1] = point
        else:
            runs.append([point, point])
    body = "".join(
        escape(low) if low == high else escape(low) + "-" + escape(high)
        for low, high in runs
    )
    return "[" + body + "]"


def check_closed(candidates: list[int]) -> None:
    """Both engines fold the candidate set onto itself and nothing else.

    Without this the table would be right only for the code points it already
    knew about, since every orbit above is read against the candidate array. A
    code point folded by an engine and missed by all four string methods would
    be invisible to both measurements and wrong in the same direction in both.
    """
    import pyarrow as pa
    import pyarrow.compute as pc

    every = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]
    wanted = set(candidates)

    def as_python(point: int) -> str:
        return "\\u%04x" % point if point < 0x10000 else "\\U%08x" % point

    text = "".join(chr(point) for point in every)
    klass = as_class(candidates, as_python)
    theirs = {ord(ch) for ch in re.findall(klass, text, re.IGNORECASE)}
    if theirs != wanted:
        raise SystemExit("Python folds outside the cased set")

    array = pa.array([chr(point) for point in every], type=pa.string())
    mask = pc.match_substring_regex(
        array, "(?i)" + as_class(candidates, lambda p: r"\x{%X}" % p)
    ).to_pylist()
    ours = {every[i] for i, matched in enumerate(mask) if matched}
    if ours != wanted:
        raise SystemExit("RE2 folds outside the cased set")


DOTTED = (0x0049, 0x0069, 0x0130, 0x0131)


def check_difference(
    theirs: dict[int, tuple[int, ...]], ours: dict[int, tuple[int, ...]]
) -> None:
    """The two engines differ on the dotted and dotless I and nowhere else."""
    differ = sorted(
        point for point in theirs if theirs[point] != ours.get(point, (point,))
    )
    if tuple(differ) != DOTTED:
        raise SystemExit(
            "the two engines now differ on %d code points rather than the four "
            "dotted I ones: %s" % (len(differ), ["U+%04X" % p for p in differ])
        )
    if theirs[0x0069] != DOTTED:
        raise SystemExit("Python no longer folds all four dotted I code points")
    if ours[0x0069] != (0x0049, 0x0069):
        raise SystemExit("RE2 no longer folds the plain I and i on their own")
    for point in (0x0130, 0x0131):
        if ours[point] != (point,):
            raise SystemExit("RE2 now folds U+%04X onto something" % point)


def cycle_of(orbits: dict[int, tuple[int, ...]]) -> dict[int, int]:
    """The successor of every cased code point in its own group.

    The successor is the next member counting upwards, wrapping round at the
    top, so a code point whose group is only itself is its own successor. That
    makes the walk that reads a group out of this table terminate on every code
    point without a length beside it.
    """
    out: dict[int, int] = {}
    for point, group in orbits.items():
        out[point] = group[(group.index(point) + 1) % len(group)]
    return out


EVEN_ODD = -0x40000000
"""The delta that is not a delta. See the header written above."""


def runs_of(cycle: dict[int, int]) -> list[tuple[int, int, int]]:
    """The successor written as runs of low, high and delta.

    A stretch of the alphabet laid out as upper and lower in pairs is one run
    with the marker on it, and anything else is a stretch over which adding the
    same number to a code point gives its successor. Those two between them
    cover the whole table in a few hundred runs.
    """
    points = sorted(cycle)
    out: list[tuple[int, int, int]] = []
    at = 0
    while at < len(points):
        low = points[at]
        delta = cycle[low] - low
        if delta == 1 and low % 2 == 0:
            end = at
            while end + 1 < len(points) and points[end + 1] == points[end] + 1:
                nxt = points[end + 1]
                if cycle[nxt] - nxt != (1 if nxt % 2 == 0 else -1):
                    break
                end += 1
            if end > at:
                out.append((low, points[end], EVEN_ODD))
                at = end + 1
                continue
        end = at
        while (
            end + 1 < len(points)
            and points[end + 1] == points[end] + 1
            and cycle[points[end + 1]] - points[end + 1] == delta
        ):
            end += 1
        out.append((low, points[end], delta))
        at = end + 1
    return out


def successor(runs: list[tuple[int, int, int]], point: int) -> int:
    """What the runs say the successor of a code point is.

    This is the generator's own copy of what `program.mojo` does with the table,
    written so that the check below compares the table against the measurement
    rather than against the code that produced it.
    """
    for low, high, delta in runs:
        if low <= point <= high:
            if delta == EVEN_ODD:
                return point + 1 if point % 2 == 0 else point - 1
            return point + delta
    return point


def check_runs(
    runs: list[tuple[int, int, int]], orbits: dict[int, tuple[int, ...]]
) -> None:
    """Walking the runs gives back every group that was measured.

    Without this the compression would be trusted on the strength of having been
    written carefully, and a run that swallowed one code point too many would be
    a wrong answer for one letter rather than a failure anybody notices.
    """
    for point, group in orbits.items():
        walked = [point]
        at = successor(runs, point)
        while at != point:
            if at in walked or len(walked) > 8:
                raise SystemExit("the cycle at U+%04X does not come back" % point)
            walked.append(at)
            at = successor(runs, at)
        if tuple(sorted(walked)) != group:
            raise SystemExit("the runs read U+%04X as a different group" % point)
    covered = {
        point
        for low, high, _ in runs
        for point in range(low, high + 1)
    }
    if covered != set(orbits):
        raise SystemExit("the runs cover code points that are not cased")


def emit(name: str, values: list[int], doc: str) -> str:
    """One array of code points, with its docstring."""
    body = "\n".join(
        f"    {value}," if value < 0 else f"    0x{value:04X}," for value in values
    )
    out = f"comptime {name}: InlineArray[Int32, {len(values)}] = [\n{body}\n]\n"
    return out + f'"""{doc}"""\n\n'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("firepanda/kernel/regex/folddata.mojo"),
        help="where to write the table",
    )
    args = parser.parse_args()

    theirs = python_orbits()
    candidates = sorted(
        set(theirs)
        | {
            point
            for point in range(0x110000)
            if chr(point).lower() != chr(point)
            or chr(point).upper() != chr(point)
            or chr(point).casefold() != chr(point)
            or chr(point).title() != chr(point)
        }
    )
    if set(candidates) != set(theirs):
        raise SystemExit("a code point has a case mapping and is not cased to re")

    check_closed(candidates)
    ours = re2_orbits(candidates)
    check_difference(theirs, ours)

    runs = runs_of(cycle_of(theirs))
    check_runs(runs, theirs)

    sizes: dict[int, int] = {}
    for group in set(theirs.values()):
        sizes[len(group)] = sizes.get(len(group), 0) + 1
    counted = ", ".join(
        "%d of %d" % (sizes[size], size) for size in sorted(sizes)
    )
    marked = sum(1 for _, _, delta in runs if delta == EVEN_ODD)

    import pyarrow

    body = HEADER.format(
        even_odd="%d" % EVEN_ODD,
        plain="%d" % (len(runs) + sum(
            high - low for low, high, delta in runs if delta == EVEN_ODD
        )),
        runs="%d" % len(runs),
        summary=textwrap.fill(
            "There are %d cased code points in %d groups, %s. The largest is the "
            "four the dotted I family makes, and the singletons are code points "
            "with a case mapping whose other half is not one character long. The "
            "cycle over all of them is %d runs, %d of which carry the marker."
            % (
                len(candidates),
                len(set(theirs.values())),
                counted,
                len(runs),
                marked,
            ),
            width=75,
        ),
        python="%d.%d.%d" % sys.version_info[:3],
        unicode=unicodedata.unidata_version,
        pyarrow=pyarrow.__version__,
    )
    body += "comptime FOLD_EVEN_ODD: Int32 = %d\n" % EVEN_ODD
    body += (
        '"""The delta that means the run alternates upper and lower in pairs.\n\n'
        + textwrap.fill(
            "A code point carrying this one has the code point above it for a "
            "successor when it is even and the one below it when it is odd. It "
            "is a number no real delta can be, since no successor is that far "
            "from its code point, and it is the difference between a few "
            "hundred runs and a few thousand.",
            width=75,
            initial_indent="",
            subsequent_indent="",
        )
        + '\n"""\n\n'
    )
    body += emit(
        "FOLD_LOW",
        [low for low, _, _ in runs],
        "Where each run starts, sorted, so that finding the run a code point is "
        "in is a binary search. A code point in no run is its own whole group "
        "and needs no table at all, which is every code point but the cased "
        "ones.",
    )
    body += emit(
        "FOLD_HIGH",
        [high for _, high, _ in runs],
        "Where each run ends, which is the last code point it covers rather "
        "than one past it.",
    )
    body += emit(
        "FOLD_DELTA",
        [delta for _, _, delta in runs],
        "What to add to a code point in the run to get its successor, or "
        "`FOLD_EVEN_ODD`. This is Python's reading. RE2 agrees with it "
        "everywhere but the four dotted I code points, which `program.mojo` "
        "handles where it picks the engine.",
    )
    # One trailing newline and no more, because `mojo format` strips a blank
    # line at the end of a file and a generator whose output the formatter
    # rewrites is a diff waiting to happen every time somebody runs both.
    args.out.write_text(body.rstrip("\n") + "\n")
    print(
        "%d cased code points in %d groups, %d runs, %d of them marked"
        % (len(candidates), len(set(theirs.values())), len(runs), marked)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
