"""Writes the table of code points whose case folding is not their lower case.

Case folding is the third case operation and it is not a case. `upper` and `lower`
write a row in a case a reader can see, and folding writes a row in a form nobody is
meant to read, whose only job is that two rows a reader would call the same fold to
the same bytes. That is why `ß` folds to `ss` and why a folded row can be longer than
the row that went in, which is the thing folding has and the other two do not.

pandas answers this out of Python rather than out of Arrow, and not by choice: pyarrow
has no casefold kernel, so a text column falls back to Python's own `str.casefold`
whatever dtype it is held as. Both pandas backends therefore agree here, which is the
opposite of the situation `tools/gen_casefix.py` exists for, and Python is the oracle
rather than the thing being corrected.

The table below is the difference between folding and the lower case this library
already writes, which is Arrow's. Everything not in it folds to exactly what it lowers
to, so the kernel asks this table first and the lower case path second. It needs
pyarrow to read that lower case, so it is not run by CI and the generated file is
committed. Run it when either side moves:

    uv run --no-project --python 3.13 --with pyarrow python tools/gen_casefold.py

It also checks the rule the kernel rests on, which is that folding a row is folding
each of its characters and sticking the answers together, over every code point and
over four thousand random words, and refuses to write anything if that stops holding.
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

HEADER = '''"""Where folding a character is not lowering it.

Case folding is what `str.casefold` does and it is not a case anybody writes
text in. Its one promise is that two rows a reader would call the same fold to
the same bytes, so `Straße` and `STRASSE` both fold to `strasse`, and the price
of that promise is that a row can come out longer than it went in. `upper` and
`lower` in this library never do, because pandas answers those out of Arrow and
Arrow uses the simple mappings, and folding is the one case operation where the
full mappings are the right answer rather than the wrong one.

That is not an inconsistency, it is what pandas does. pyarrow has no casefold
kernel, so a pandas text column falls back to Python for this one method while
every other case method stays in Arrow. Both pandas backends agree here as a
result, and this file is generated against Python rather than against Arrow.

{count} code points fold to something other than their lower case, {expanding} of
them to more than one code point and none to more than three. Everything else
folds to exactly what it lowers to, which is why this is a difference table
rather than a folding table: `chars.mojo` asks this first and falls through to
the lower case path, corrections and all, for every code point that is not here.

There is no byte test here of the kind `casefix.mojo` carries. The lowest code
point in that table is the sharp s at U+00DF, so an element with no byte at or
above 0xC3 cannot hold one and a good deal of ordinary accented text leaves on
that test alone. The lowest code point here is the micro sign at U+00B5, whose
lead byte is 0xC2, and 0xC2 is the lowest lead byte a non ASCII character can
have at all, so asking whether an element could hold one of these and asking
whether it is not ASCII are the same question. `chars.mojo` asks the second one
because it is the cheaper spelling of it.

The three tables are one list of code points, one list of offsets and one run of
answers. The answers for the code point at index `i` are the run of `FOLDED_TO`
between `FOLDED_AT[i]` and `FOLDED_AT[i + 1]`, which is how a table whose rows
are different lengths is held without an allocation per row.

Generated by tools/gen_casefold.py against Python {python}, with pyarrow
{pyarrow} read for the lower case half. It is committed rather than built,
because the generator needs pyarrow and the Mojo build does not have it. The
Python tests assert several of these rows against a running pandas, so a change
on either side fails a test rather than passing quietly.
"""

'''


def table(name: str, values: list[int]) -> str:
    """One comptime array, a code point to a line.

    A line each rather than a row of eight because that is the shape the Mojo
    formatter puts a long literal in, and a generator whose output the formatter
    rewrites is a generator nobody can tell has been run.
    """
    body = "\n".join(f"    0x{v:04X}," for v in values)
    return f"comptime {name}: InlineArray[UInt32, {len(values)}] = [\n{body}\n]\n"


def check_composition(points: list[int], folds: dict[int, str]) -> None:
    """Asserts that folding a row is folding its characters one at a time.

    The kernel walks a row a character at a time and sticks the answers
    together, which is only right if folding has no rule that looks at a
    neighbour. Unicode says it has none. This measures it anyway, over every
    code point on its own and then over a few thousand words built out of the
    ones that fold to something other than themselves, because a rule that held
    for single characters and failed for pairs is exactly the shape of defect
    this walk would have.
    """
    rng = random.Random(0)
    interesting = [c for c in points if chr(c).casefold() != chr(c)]
    words = ["".join(chr(rng.choice(interesting)) for _ in range(6)) for _ in range(4000)]
    for word in words:
        got = "".join(folds.get(ord(c), c.casefold()) for c in word)
        if got != word.casefold():
            raise SystemExit(f"folding is not per character for {word!r}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("firepanda/kernel/casefold.mojo"),
        help="where to write the table",
    )
    args = parser.parse_args()

    import pyarrow as pa
    import pyarrow.compute as pc

    points = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]
    chars = [chr(c) for c in points]
    dropped = pc.utf8_lower(pa.array(chars)).to_pylist()

    keys: list[int] = []
    offsets: list[int] = [0]
    answers: list[int] = []
    folds: dict[int, str] = {}
    for cp, lowered in zip(points, dropped, strict=True):
        folded = chr(cp).casefold()
        if folded == lowered:
            continue
        keys.append(cp)
        folds[cp] = folded
        answers.extend(ord(c) for c in folded)
        offsets.append(len(answers))

    check_composition(points, folds)

    expanding = sum(1 for cp in keys if len(folds[cp]) > 1)
    body = HEADER.format(
        count=len(keys),
        expanding=expanding,
        python=".".join(str(part) for part in sys.version_info[:3]),
        pyarrow=pa.__version__,
    )
    body += table("FOLDED_FROM", keys)
    body += '"""The code points that fold to something other than their lower case."""\n\n'
    body += table("FOLDED_AT", offsets)
    body += (
        '"""Where each answer starts in `FOLDED_TO`, with the end on the tail.\n\n'
        "One longer than the list of code points, so the answer for an entry is\n"
        "always the run between this offset and the next one and the last entry\n"
        "needs no special case.\n"
        '"""\n\n'
    )
    body += table("FOLDED_TO", answers)
    body += (
        '"""The folded answers end to end, read through `FOLDED_AT`.\n\n'
        "Longer than the list of code points, because a fold can be two or three\n"
        "code points where a case mapping in this library is always one.\n"
        '"""\n\n'
    )
    args.out.write_text(body)
    print(f"{len(keys)} folds, {expanding} expanding, {len(answers)} code points of answer")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
