"""Writes the tables that say which class a character belongs to.

The class questions of the `str` accessor are not questions about a mapping, they are
questions about what a character is, and a class is the one thing the Mojo standard
library's character data does not have enough of. It disagrees with Arrow about 1384 code
points on the three case questions alone, which is what issue #748 measured, and that is
not a list of exceptions to patch, it is whole blocks of Unicode that one side knows about
and the other does not.

The answer here is the same shape as Arrow's own: a class is a sorted run of ranges, the
ranges are dense because Unicode assigns properties in blocks, and membership is a binary
search rather than a table with a row per code point. Eight classes at a few hundred ranges
each come to a handful of kilobytes, against the megabyte a code point per row would cost.

The classes are read out of pyarrow rather than out of the published Unicode data files.
That is deliberate and it is not laziness. pandas answers these names out of Arrow, so
Arrow is not an approximation of the right answer here, it is the right answer, and a
table generated from the UCD would be a second opinion this library would then have to
reconcile with the first. Reading Arrow means a code point cannot disagree, ever, rather
than agreeing until utf8proc and the UCD release we happened to read drift apart.

    uv run --no-project --python 3.13 --with pyarrow python tools/gen_charclass.py

It checks the string level rules the kernel rests on before it writes anything, over every
code point on its own and over sixty thousand random words built out of the classes that
matter, and refuses to write if pyarrow disagrees with any of them. Two of those rules are
identities rather than walks: alphanumeric is exactly alphabetic or numeric, so there is no
ALNUM class, and no character is both, so a row of letters and a row of digits cannot be
confused by a rule that reads either one.
"""

from __future__ import annotations

import argparse
import random
import textwrap
from pathlib import Path

HEADER = '''"""Which class each character belongs to.

Most of the string predicates are not about what a character maps to, they are
about what it is. `isspace` asks whether every character is a space, `islower`
and `isupper` ask about case but not about any case mapping, and `isalpha` and
the four number questions ask about nothing else at all. All of them want a
class rather than a table of pairs.

The classes here are Arrow's, read straight out of pyarrow by
tools/gen_charclass.py, because pandas answers all of these names out of Arrow
and a class read from anywhere else would be a second opinion rather than the
answer. The Mojo standard library has its own, which is close, and close is
worth 1384 code points of disagreement across the three case questions alone.

Each class is a sorted run of ranges held flat, as a start, one past an end,
the next start, and so on, so an even number of entries and a code point is in
the class when the number of entries at or below it is odd. Unicode hands out
properties in blocks, so the ranges are few next to the code points they cover:
{summary}

Below the first 128 code points there is no search at all. Each class carries
its ASCII half as a pair of 64 bit words, which is one shift and one mask for
the characters nearly all real text is made of, and the ranges are only read
when a character is not ASCII.

The two case classes leave a gap on purpose. A titlecase character like `{title}`
is neither lower nor upper to Arrow, so it is in neither class, and `TITLE_ONLY`
is the {titles} code points of that kind. A row holding one is not lower and not
upper either, which is why both questions have to read a class they are not
named after.

There is no class here for the alphanumeric characters, because a character is
alphanumeric exactly when it is alphabetic or numeric and the two classes have
nothing in common. Both of those are measured against pyarrow rather than
assumed, since a subset relation nobody checked is how a table gets one entry
wrong for a decade. DECIMAL is inside DIGIT is inside NUMERIC for the same
reason and is stored separately anyway, because three narrowing searches are
cheaper than one search and two range tests and the whole of the three is under
three kilobytes.

DIGIT is the one of these a Python programmer will read wrong. Arrow calls
anything written as a single number sign a digit, so `½` and `²` are both
digits to it, where Python calls `½` numeric and not a digit. That is 877 code
points of disagreement, and pandas answers Arrow, so the table is Arrow's.

Generated by tools/gen_charclass.py against pyarrow {pyarrow}, committed rather
than built because the Mojo build has no pyarrow in it. The generator asserts
the string level rules against pyarrow over every code point and sixty thousand
random words before it writes, and the Python tests assert a sample of them
against a running pandas, so a change on either side fails rather than passes
quietly.
"""

'''


def ranges(points: list[int]) -> list[tuple[int, int]]:
    """The sorted code points folded into the runs they make up."""
    out: list[list[int]] = []
    for cp in points:
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return [(a, b) for a, b in out]


def edges(points: list[int]) -> list[int]:
    """The runs written flat, as a start and one past an end and so on."""
    flat: list[int] = []
    for low, high in ranges(points):
        flat.append(low)
        flat.append(high + 1)
    return flat


def ascii_words(points: set[int]) -> tuple[int, int]:
    """The first 128 code points of a class as two 64 bit words."""
    low = sum(1 << cp for cp in points if cp < 64)
    high = sum(1 << (cp - 64) for cp in points if 64 <= cp < 128)
    return low, high


def emit(name: str, points: list[int], doc: str) -> str:
    """One class, its two ASCII words and its ranges, with the docstring."""
    low, high = ascii_words(set(points))
    flat = edges(points)
    body = "\n".join(f"    0x{v:04X}," for v in flat)
    out = f"comptime {name}_ASCII_LOW: UInt64 = 0x{low:016X}\n"
    out += f'"""The first 64 code points of {name.lower()}, a bit each."""\n\n'
    out += f"comptime {name}_ASCII_HIGH: UInt64 = 0x{high:016X}\n"
    out += f'"""Code points 64 to 127 of {name.lower()}, a bit each."""\n\n'
    out += f"comptime {name}_EDGES: InlineArray[UInt32, {len(flat)}] = [\n{body}\n]\n"
    out += f'"""{doc}"""\n\n'
    return out


def check(sets: dict[str, set[int]], points: list[int]) -> None:
    """Asserts the string level rules against pyarrow before writing.

    The kernel walks an element a character at a time and folds the classes
    into an answer, and the folding is the part worth doubting. Whether a row
    of several characters is lower case is not whether each character is, it is
    whether one of them is and none of them is upper or titlecase, and an empty
    row and a row of digits both answer no for the same reason. The five
    questions that are not about case are the simpler rule, which is that the
    row is not empty and every character is in the class, and that is worth
    measuring too rather than assumed by analogy with the case ones.

    Measured over every code point on its own and then over sixty thousand
    random words drawn from the classes that make the rules interesting.
    """
    import pyarrow as pa
    import pyarrow.compute as pc

    lower, upper, titles, spaces = (
        sets["LOWER"],
        sets["UPPER"],
        sets["TITLE_ONLY"],
        sets["SPACE"],
    )

    def is_lower(row: str) -> bool:
        seen = [ord(c) for c in row]
        return any(c in lower for c in seen) and not any(c in upper or c in titles for c in seen)

    def is_upper(row: str) -> bool:
        seen = [ord(c) for c in row]
        return any(c in upper for c in seen) and not any(c in lower or c in titles for c in seen)

    def every(members: set[int]):
        def rule(row: str) -> bool:
            return len(row) > 0 and all(ord(c) in members for c in row)

        return rule

    rules = {
        "utf8_is_lower": is_lower,
        "utf8_is_upper": is_upper,
        "utf8_is_space": every(spaces),
        "utf8_is_alpha": every(sets["ALPHA"]),
        "utf8_is_numeric": every(sets["NUMERIC"]),
        "utf8_is_digit": every(sets["DIGIT"]),
        "utf8_is_decimal": every(sets["DECIMAL"]),
        "utf8_is_alnum": every(sets["ALPHA"] | sets["NUMERIC"]),
    }

    rng = random.Random(7)
    wide = lower | upper | titles | spaces | sets["NUMERIC"]
    # The alphabetic class is 145672 code points and every other class here is
    # under 2400, so drawing from the union unweighted would give words made of
    # letters and nothing else and would measure one rule eight times.
    pool = sorted(wide | set(rng.sample(sorted(sets["ALPHA"]), 2000)))
    pool += [ord("a"), ord("Z"), ord("1"), ord(" "), ord("-")]
    rows = [chr(c) for c in points]
    rows += ["".join(chr(rng.choice(pool)) for _ in range(rng.randint(0, 5))) for _ in range(60000)]
    column = pa.array(rows)
    for name, rule in rules.items():
        for row, want in zip(rows, getattr(pc, name)(column).to_pylist(), strict=True):
            if rule(row) != want:
                raise SystemExit(f"{name} is not the rule we thought for {row!r}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("firepanda/kernel/charclass.mojo"),
        help="where to write the tables",
    )
    args = parser.parse_args()

    import pyarrow as pa
    import pyarrow.compute as pc

    points = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]
    column = pa.array([chr(c) for c in points])

    def held(name: str) -> set[int]:
        answers = getattr(pc, name)(column).to_pylist()
        return {cp for cp, yes in zip(points, answers, strict=True) if yes}

    lower = held("utf8_is_lower")
    upper = held("utf8_is_upper")
    title = held("utf8_is_title")
    space = held("utf8_is_space")
    alpha = held("utf8_is_alpha")
    numeric = held("utf8_is_numeric")
    digit = held("utf8_is_digit")
    decimal = held("utf8_is_decimal")
    alnum = held("utf8_is_alnum")
    if not upper <= title:
        raise SystemExit("an upper case character that is not titlecase")
    if lower & title:
        raise SystemExit("a character that is both lower case and titlecase")
    if alnum != alpha | numeric:
        raise SystemExit("alphanumeric is not alphabetic or numeric after all")
    if alpha & numeric:
        raise SystemExit("a character that is both a letter and a number")
    if not decimal <= digit <= numeric:
        raise SystemExit("the three number classes are not nested after all")

    sets = {
        "LOWER": lower,
        "UPPER": upper,
        "TITLE_ONLY": title - upper,
        "SPACE": space,
        "ALPHA": alpha,
        "NUMERIC": numeric,
        "DIGIT": digit,
        "DECIMAL": decimal,
    }
    check(sets, points)

    lines = []
    for name, members in sets.items():
        held_ranges = len(ranges(sorted(members)))
        lines.append(f"{name.lower()} is {len(members)} code points in {held_ranges} ranges")
    sentence = ", and ".join([", ".join(lines[:-1]), lines[-1]]) + "."
    body = HEADER.format(
        summary="\n".join(textwrap.wrap(sentence, width=75)),
        title=chr(min(sets["TITLE_ONLY"])),
        titles=len(sets["TITLE_ONLY"]),
        pyarrow=pa.__version__,
    )
    docs = {
        "LOWER": "The lower case characters, as ranges. Fewer than a reader expects, "
        "because a modifier letter that looks lower case is not cased at all.",
        "UPPER": "The upper case characters, as ranges. A titlecase character is not "
        "one of these, which is what `TITLE_ONLY` is for.",
        "TITLE_ONLY": "The titlecase characters, which are neither lower nor upper. "
        "The four Croatian digraphs and the Greek letters with an iota under them.",
        "SPACE": "The space characters, as ranges. Wider than the ASCII six by the "
        "non breaking space, the en and em quads and the rest of the U+2000 run.",
        "ALPHA": "The alphabetic characters, as ranges. By far the largest class "
        "here and not by far the most ranges, because alphabets arrive in blocks.",
        "NUMERIC": "The numeric characters, as ranges. Wider than the digits by the "
        "239 that are a number and a letter at once, the Roman numerals and the rest.",
        "DIGIT": "The digit characters, as ranges. Wider than Python's digits by the "
        "915 written as one sign rather than a place, the fractions and superscripts.",
        "DECIMAL": "The decimal digit characters, as ranges. The narrowest of the "
        "three and the only one whose members can be a place in a base ten number.",
    }
    for name, members in sets.items():
        body += emit(name, sorted(members), docs[name])
    args.out.write_text(body)
    for line in lines:
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
