"""Writes the table that says what one code point's simple lowercase is.

This is the second case table in the engine and it exists because a
backreference under `(?i)` does not ask the question the fold table answers. A
literal under that flag is compiled into the set of everything that folds onto
it, which is the whole orbit, and a backreference is compared at run time by
lowering both characters and seeing whether they land in the same place. Those
two are not the same question and upstream answers them with two different
functions, `_sre.unicode_tolower` for the reference and the fold orbit for the
literal, so a library copying upstream needs both.

The difference is measurable and is not an edge nobody meets. On CPython 3.13
`(?i)ss` matches `sſ` because the long s is in the orbit of `s`, while
`(?i)(s)\\1` does not match it because the long s lowers to itself. The same
goes for sigma and final sigma. It goes the other way for the dotted capital I,
which lowers to a plain `i`, so `(?i)(\\u0130)\\1` matches `\\u0130i`.

Only Python is asked here, unlike the fold generator next door, and the reason
is that a backreference is a construct RE2 has not got at all. There is no
second engine to reconcile with and therefore no second table.

The run encoding is the fold table's with one marker of its own. Long stretches
of the alphabet are laid out as an upper code point followed by its lower, and
over such a stretch only the even one moves. Writing those as ordinary runs
gives one run per letter, which is 668 runs where the marker makes 214.

    uv run --no-project --python 3.13 python tools/gen_regexlower.py
"""

from __future__ import annotations

import argparse
import sys
import textwrap
import unicodedata
from pathlib import Path

import _sre

HEADER = [
    "What one code point's simple lowercase is.",
    "The other case table in this engine, and the one the fold table cannot "
    "answer. `(?i)` on a literal is settled while the pattern is being "
    "compiled, by turning the literal into the set of everything that folds "
    "onto it, and folddata.mojo is that set. `(?i)` on a backreference is "
    "settled while the row is being walked, by lowering the character the "
    "group matched and the character in front of the cursor and comparing the "
    "two, and that is this table.",
    "Upstream uses two different functions for the two and they disagree on "
    "real text. `(?i)ss` matches `s\\u017f` because the long s is in the orbit "
    "of `s`, while `(?i)(s)\\1` does not match it because the long s lowers to "
    "itself. `(?i)(\\u03c3)\\1` does not match sigma followed by final sigma "
    "for the same reason. And it goes the other way round for the dotted "
    "capital I, which lowers to a plain `i`, so `(?i)(\\u0130)\\1` matches "
    "`\\u0130i`. Document 97.",
    "Only Python is asked, because a backreference is a construct RE2 has not "
    "got, so there is no second engine here to reconcile with and no second "
    "table.",
    "The encoding is the fold table's. A run is a low, a high and a delta, the "
    "delta is added to a code point to get its lowercase, and a code point in "
    "no run is its own lowercase, which is every code point but the {moved} "
    "that move. One delta is not a number: `{even_only}` means the run is a "
    "stretch laid out as an upper code point followed by its lower, so an even "
    "code point lowers to the one above it and an odd one lowers to itself. "
    "That marker is what turns {plain} runs into {runs}, since without it "
    "every letter of such a stretch is a run on its own.",
    "There are {moved} code points whose lowercase is not themselves, covered "
    "by {runs} runs, {marked} of which carry the marker. The other {plainruns} "
    "take {deltas} different deltas between them, from {least} to {most}, and "
    "{usualruns} of those take the delta of {usual} that the marker itself "
    "stands for, left as plain runs because the stretch of pairs there was too "
    "short to be worth marking.",
    "Generated by tools/gen_regexlower.py against CPython {python} with "
    "Unicode {unicode}, committed rather than built because the Mojo build has "
    "no Python in it. It is the same interpreter folddata.mojo was generated "
    "against and the same skew applies: a later CPython carries a later "
    "Unicode and moves a few dozen code points, so this table is the answer of "
    "the version named here rather than of whichever version happens to be "
    "running. The generator checks that walking these runs reproduces the "
    "lowercase of every code point in Unicode, so a release that moves the "
    "answer fails there rather than drifting.",
]
"""The file's docstring, a paragraph to an entry, wrapped where it is written."""


EVEN_ONLY = -0x40000000
"""The delta that is not a delta. See the header written above."""


def runs_of(lower: dict[int, int]) -> list[tuple[int, int, int]]:
    """The lowercase written as runs of low, high and delta.

    A stretch laid out as an upper code point followed by its lower is one run
    with the marker on it, and the run covers the odd code points in it as well
    even though none of them moves, because that is what makes it one run. A
    stretch over which adding the same number to a code point gives its
    lowercase is an ordinary run. Those two between them cover the table in a
    couple of hundred runs.
    """
    points = sorted(lower)
    out: list[tuple[int, int, int]] = []
    at = 0
    while at < len(points):
        low = points[at]
        if low % 2 == 0 and lower[low] == low + 1:
            end = at
            while (
                end + 1 < len(points)
                and points[end + 1] == points[end] + 2
                and points[end + 1] % 2 == 0
                and lower[points[end + 1]] == points[end + 1] + 1
                and points[end] + 1 not in lower
            ):
                end += 1
            if end > at:
                out.append((low, points[end] + 1, EVEN_ONLY))
                at = end + 1
                continue
        delta = lower[low] - low
        end = at
        while (
            end + 1 < len(points)
            and points[end + 1] == points[end] + 1
            and lower[points[end + 1]] - points[end + 1] == delta
        ):
            end += 1
        out.append((low, points[end], delta))
        at = end + 1
    return out


def lowered(runs: list[tuple[int, int, int]], point: int) -> int:
    """What the runs say the lowercase of a code point is.

    The generator's own copy of what `backtrack.mojo` does with the table,
    written so that the check below compares the table against the measurement
    rather than against the code that produced it.
    """
    for low, high, delta in runs:
        if low <= point <= high:
            if delta == EVEN_ONLY:
                return point + 1 if point % 2 == 0 else point
            return point + delta
    return point


def check_runs(runs: list[tuple[int, int, int]]) -> None:
    """The runs give back the lowercase of every code point there is.

    Every code point rather than every moved one, because the failure a
    compression like this makes is a run that swallows a neighbour, and a
    neighbour that does not move is invisible to a check that only asks about
    the ones that do.
    """
    for point in range(0x110000):
        if lowered(runs, point) != _sre.unicode_tolower(point):
            raise SystemExit(
                "the runs read U+%04X as U+%04X where upstream reads U+%04X"
                % (point, lowered(runs, point), _sre.unicode_tolower(point))
            )


def check_cased(moved: dict[int, int]) -> None:
    """Everything that moves is something the fold table already knows about.

    The two tables answer different questions and they are built over the same
    code points, since upstream groups the orbits by lowercase in the first
    place. A code point that lowered onto something without being cased would be
    one this engine folds one way and lowers another, which is the shape of
    mistake neither table could show on its own.
    """
    for point in moved:
        if not _sre.unicode_iscased(point):
            raise SystemExit(
                "U+%04X lowers onto something and is not cased" % point
            )


def wrapped(paragraphs: list[str]) -> str:
    """Paragraphs laid out as a Mojo docstring, hand width rather than ruff's."""
    return "\n\n".join(textwrap.fill(one, width=79) for one in paragraphs)


def emit(name: str, values: list[int], doc: str) -> str:
    """One array of code points, with its docstring."""
    body = "\n".join(
        f"    {value}," if value < 0 else f"    0x{value:04X}," for value in values
    )
    out = f"comptime {name}: InlineArray[Int32, {len(values)}] = [\n{body}\n]\n"
    return out + f'"""{wrapped([doc])}"""\n\n'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("firepanda/kernel/regex/lowerdata.mojo"),
        help="where to write the table",
    )
    args = parser.parse_args()

    moved = {
        point: _sre.unicode_tolower(point)
        for point in range(0x110000)
        if _sre.unicode_tolower(point) != point
    }
    check_cased(moved)
    runs = runs_of(moved)
    check_runs(runs)

    marked = sum(1 for _, _, delta in runs if delta == EVEN_ONLY)
    plain = len(runs) + sum(
        (high - low + 1) // 2 - 1
        for low, high, delta in runs
        if delta == EVEN_ONLY
    )
    deltas = [delta for _, _, delta in runs if delta != EVEN_ONLY]

    body = '"""'
    body += wrapped(
        [
            one.format(
                moved=len(moved),
                even_only=EVEN_ONLY,
                plain=plain,
                runs=len(runs),
                marked=marked,
                plainruns=len(deltas),
                deltas=len(set(deltas)),
                least=min(deltas),
                most=max(deltas),
                usual=max(set(deltas), key=deltas.count),
                usualruns=deltas.count(max(set(deltas), key=deltas.count)),
                python="%d.%d.%d" % sys.version_info[:3],
                unicode=unicodedata.unidata_version,
            )
            for one in HEADER
        ]
    )
    body += '\n"""\n\n'
    body += "comptime LOWER_RUNS: Int = %d\n" % len(runs)
    body += '"""'
    body += wrapped(
        [
            "How many runs there are, written out so that a reader of the table"
            " does not have to materialize one of the arrays to ask.",
        ]
    )
    body += '\n"""\n\n'
    body += "comptime LOWER_EVEN_ONLY: Int32 = %d\n" % EVEN_ONLY
    body += '"""'
    body += wrapped(
        [
            "The delta that means the run alternates upper and lower in pairs.",
            "A code point in a run carrying this one lowers to the code point "
            "above it when it is even and lowers to itself when it is odd. It "
            "is a number no real delta can be, since no lowercase is that far "
            "from its code point, and it is the difference between a couple of "
            "hundred runs and most of a thousand.",
        ]
    )
    body += '\n"""\n\n'
    body += emit(
        "LOWER_LOW",
        [low for low, _, _ in runs],
        "Where each run starts, sorted, so that finding the run a code point is "
        "in is a binary search. A code point in no run lowers to itself, which "
        "is every code point but the cased ones that move.",
    )
    body += emit(
        "LOWER_HIGH",
        [high for _, high, _ in runs],
        "Where each run ends, which is the last code point it covers rather "
        "than one past it.",
    )
    body += emit(
        "LOWER_DELTA",
        [delta for _, _, delta in runs],
        "What to add to a code point in the run to get its lowercase, or the "
        "marker above when the run alternates.",
    )
    # One newline at the end rather than the blank line `emit` leaves between
    # arrays, so that regenerating gives back exactly what the formatter left.
    args.out.write_text(body.rstrip("\n") + "\n")
    print(
        "wrote %s, %d runs over %d code points"
        % (args.out, len(runs), len(moved))
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
