"""Writes the three class tables Python's own regular expression engine uses.

`firepanda/kernel/charclass.mojo` already holds eight classes and none of them is
the right answer here, which took measuring rather than reading to find out.
Those eight are Arrow's, because the `str` accessor's class questions are
answered out of Arrow, and `\\w` in a pattern is not one of those questions. It
is whatever the engine running the pattern thinks a word character is, and
pandas runs two engines and picks between them by method name.

RE2's three are ASCII and `firepanda/kernel/regex/program.mojo` writes them out
by hand, which is four ranges of literals and needs no table at all. Python's
three are Unicode and are what this file is for.

The three definitions are short enough to state and were checked rather than
copied: `\\w` is exactly what `str.isalnum` says plus the underscore, `\\d` is
exactly `str.isdecimal`, and `\\s` is exactly `str.isspace`. The generator
asserts all three over every code point before it writes anything, so a future
CPython that widens one of them without widening the other fails here rather
than passing quietly.

The tables are read out of the running CPython's `re` module rather than out of
the published Unicode data files, for the reason tools/gen_charclass.py reads
pyarrow: pandas answers `extract`, `extractall` and `findall` by compiling the
pattern with this exact module, so this module is not an approximation of the
right answer, it is the right answer.

That has a cost worth knowing about. CPython and pyarrow are not built against
the same Unicode release, and today they are a whole version apart, so Arrow's
alphanumeric class is 9039 code points wider than Python's `\\w` and Arrow's
decimal class is 90 code points wider than Python's `\\d`. Every one of those
code points is unassigned in CPython's Unicode and assigned in Arrow's, so the
two are not disagreeing about any definition, they are disagreeing about when
they were built. The tables here will therefore move when CPython's Unicode
release moves, and the test beside them compares against a running Python so the
move is a failure rather than a drift.

    uv run --no-project --python 3.13 python tools/gen_regexclass.py
"""

from __future__ import annotations

import argparse
import re
import sys
import textwrap
import unicodedata
from pathlib import Path

HEADER = '''"""What the three Perl classes mean to Python's regular expression engine.

RE2 reads `\\\\w`, `\\\\d` and `\\\\s` as ASCII and Python reads them as Unicode, and
pandas runs both engines, so the same letter in the same accessor means two
different sets of characters depending on which method was called.
`str.count(r"\\\\w")` on a row of `café` is 3 and `str.findall(r"\\\\w")` on the very
same row is 4 characters long. Document 81 is where that was measured and says
which methods take which engine.

RE2's three are written out by hand in `program.mojo`, because four ranges of
ASCII literals is not a table. Python's three are these, and they are here
rather than beside the eight in `firepanda/kernel/charclass.mojo` because those
eight are Arrow's and these are not. The `str` accessor's class questions are
answered out of Arrow and a pattern's classes are not one of those questions.

Each class is a sorted run of low and high pairs, both ends inside the class,
which is the shape `_category_ranges` in `program.mojo` already hands back for
the ASCII three. There is no ASCII fast path here and there is one next door,
because these are read once while a pattern is being compiled and those are read
once per character of every row.

{summary}

Generated by tools/gen_regexclass.py against CPython {python} and its Unicode
{unicode}, committed rather than built because the Mojo build has no Python in
it. The generator checks that `\\\\w` is exactly alphanumeric plus the underscore,
that `\\\\d` is exactly the decimal digits and that `\\\\s` is exactly the space
characters, over every code point, before it writes. The Python tests compare a
sample against a running `re`, so a CPython built against a newer Unicode fails
rather than drifts.
"""

'''


def ranges(points: list[int]) -> list[tuple[int, int]]:
    """The sorted code points folded into the runs they make up."""
    out: list[list[int]] = []
    for cp in points:
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return [(a, b) for a, b in out]


def flat(points: list[int]) -> list[int]:
    """The runs written flat, as a low and a high and the next low and so on."""
    pairs: list[int] = []
    for low, high in ranges(points):
        pairs.append(low)
        pairs.append(high)
    return pairs


def emit(name: str, points: list[int], doc: str) -> str:
    """One class as a comptime array of low and high pairs, with its docstring."""
    values = flat(points)
    body = "\n".join(f"    0x{v:04X}," for v in values)
    out = f"comptime {name}_RANGES: InlineArray[Int32, {len(values)}] = [\n{body}\n]\n"
    out += f'"""{doc}"""\n\n'
    return out


def measured() -> dict[str, set[int]]:
    """Every code point each of the three classes holds, asked of `re` itself.

    A surrogate is left out because `chr` of one cannot be encoded and a pattern
    can never see one in a row that arrived as UTF-8 anyway.
    """
    points = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]
    out: dict[str, set[int]] = {}
    for name, pattern in (("WORD", r"\w"), ("DIGIT", r"\d"), ("SPACE", r"\s")):
        rx = re.compile(pattern)
        out[name] = {c for c in points if rx.match(chr(c))}
    return out


def check(sets: dict[str, set[int]]) -> None:
    """Asserts the three definitions against the string methods before writing.

    Every one of these is a sentence somebody would write from memory, and the
    point of checking them is that all three are true today and none of them has
    to stay true. `\\d` in particular is the one a reader gets wrong, because
    Python calls a superscript two a digit to `str.isdigit` and not to `\\d`.
    """
    points = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]
    word = {c for c in points if chr(c).isalnum()} | {ord("_")}
    if sets["WORD"] != word:
        raise SystemExit(r"\w is no longer alphanumeric plus the underscore")
    decimal = {c for c in points if chr(c).isdecimal()}
    if sets["DIGIT"] != decimal:
        raise SystemExit(r"\d is no longer exactly the decimal digits")
    digit = {c for c in points if chr(c).isdigit()}
    if sets["DIGIT"] == digit:
        raise SystemExit(r"\d and str.isdigit now agree, which they never have")
    spaces = {c for c in points if chr(c).isspace()}
    if sets["SPACE"] != spaces:
        raise SystemExit(r"\s is no longer exactly the space characters")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("firepanda/kernel/regex/classdata.mojo"),
        help="where to write the tables",
    )
    args = parser.parse_args()

    sets = measured()
    check(sets)

    lines = []
    for name in ("WORD", "DIGIT", "SPACE"):
        members = sets[name]
        lines.append(
            f"{name.lower()} is {len(members)} code points in "
            f"{len(ranges(sorted(members)))} ranges"
        )
    sentence = ", and ".join([", ".join(lines[:-1]), lines[-1]]) + "."
    body = HEADER.format(
        summary="\n".join(textwrap.wrap(sentence, width=75)),
        python="%d.%d.%d" % sys.version_info[:3],
        unicode=unicodedata.unidata_version,
    )
    docs = {
        "WORD": "The word characters, as ranges. Exactly what `str.isalnum` "
        "answers yes to, plus the underscore, which is a great deal wider than "
        "RE2's 63 and a little narrower than Arrow's alphanumeric class.",
        "DIGIT": "The digit characters, as ranges. Exactly the decimal digits "
        "and not what `str.isdigit` answers, so a superscript two is in that "
        "one and not in this one.",
        "SPACE": "The space characters, as ranges. The same 29 Arrow has today "
        "and generated here anyway, because the two agreeing is a fact about "
        "two Unicode releases rather than a rule either one follows.",
    }
    for name in ("WORD", "DIGIT", "SPACE"):
        body += emit(name, sorted(sets[name]), docs[name])
    args.out.write_text(body)
    for line in lines:
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
