# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""The registration calls, one per binding.

This is the flat sequence document 13 section 7 explains cannot be
a loop.
"""

from std.python import PythonObject
from std.python.bindings import PythonModuleBuilder

from firepanda.py.frame import PyDataFrame, open_arrow, open_csv, raise_for_test
from firepanda.py.series import PySeries


def register(mut module: PythonModuleBuilder) raises:
    """Registers every binding on the module.

    Args:
        module: The builder to register on.
    """
    module.def_function[open_csv](
        "read_csv", docstring="Reads a CSV file into a frame."
    )
    module.def_function[open_arrow](
        "from_arrow",
        docstring="Builds a frame from a pyarrow, Polars or pandas frame.",
    )
    module.def_function[raise_for_test](
        "_raise_for_test",
        docstring=(
            "Raises one classified error of the given kind. For tests only."
        ),
    )

    ref dataframe = module.add_type[PyDataFrame]("DataFrame")
    _ = dataframe.def_py_init[PyDataFrame.py_init]()
    _ = dataframe.def_method[PyDataFrame.length](
        "length", docstring="The number of rows."
    )
    _ = dataframe.def_method[PyDataFrame.width](
        "width", docstring="The number of columns."
    )
    _ = dataframe.def_method[PyDataFrame.names](
        "names", docstring="The column names, in order."
    )
    _ = dataframe.def_method[PyDataFrame.head](
        "head", docstring="The first n rows."
    )
    _ = dataframe.def_method[PyDataFrame.tail](
        "tail", docstring="The last n rows."
    )
    _ = dataframe.def_method[PyDataFrame.column](
        "column", docstring="One column, as a series."
    )
    _ = dataframe.def_method[PyDataFrame.select](
        "select", docstring="Several columns, as a frame."
    )
    _ = dataframe.def_method[PyDataFrame.arrow_c_schema](
        "arrow_c_schema", docstring="The frame's Arrow schema, in a capsule."
    )
    _ = dataframe.def_method[PyDataFrame.arrow_c_array](
        "arrow_c_array",
        docstring="The frame's Arrow schema and data, in two capsules.",
    )

    ref series = module.add_type[PySeries]("Series")
    _ = series.def_py_init[PySeries.py_init]()
    _ = series.def_method[PySeries.length](
        "length", docstring="The number of rows."
    )
    _ = series.def_method[PySeries.label](
        "label", docstring="The name of the column."
    )
    _ = series.def_method[PySeries.dtype](
        "dtype", docstring="The type, as firepanda spells it."
    )
    _ = series.def_method[PySeries.null_count](
        "null_count", docstring="How many rows are missing."
    )
    _ = series.def_method[PySeries.head]("head", docstring="The first n rows.")
    _ = series.def_method[PySeries.tail]("tail", docstring="The last n rows.")
    _ = series.def_method[PySeries.to_list](
        "to_list", docstring="Every value, copied into a Python list."
    )
