# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""The registration calls, one per binding.

This is the flat sequence document 13 section 7 explains cannot be
a loop.
"""

from std.python import PythonObject
from std.python.bindings import PythonModuleBuilder

from firepanda.py.frame import PyDataFrame, open_arrow, open_csv, raise_for_test
from firepanda.py.index import PyIndex
from firepanda.py.series import PySeries


def register(mut module: PythonModuleBuilder) raises:
    """Registers every binding on the module.

    Args:
        module: The builder to register on.
    """
    module.def_function[open_csv](
        "read_csv", docstring="Reads a CSV file into a frame."
    )
    module.def_function[open_arrow](
        "from_arrow",
        docstring="Builds a frame from a pyarrow, Polars or pandas frame.",
    )
    module.def_function[raise_for_test](
        "_raise_for_test",
        docstring=(
            "Raises one classified error of the given kind. For tests only."
        ),
    )

    ref dataframe = module.add_type[PyDataFrame]("DataFrame")
    _ = dataframe.def_py_init[PyDataFrame.py_init]()
    _ = dataframe.def_method[PyDataFrame.length](
        "length", docstring="The number of rows."
    )
    _ = dataframe.def_method[PyDataFrame.width](
        "width", docstring="The number of columns."
    )
    _ = dataframe.def_method[PyDataFrame.names](
        "names", docstring="The column names, in order."
    )
    _ = dataframe.def_method[PyDataFrame.head](
        "head", docstring="The first n rows."
    )
    _ = dataframe.def_method[PyDataFrame.tail](
        "tail", docstring="The last n rows."
    )
    _ = dataframe.def_method[PyDataFrame.column](
        "column", docstring="One column, as a series."
    )
    _ = dataframe.def_method[PyDataFrame.select](
        "select", docstring="Several columns, as a frame."
    )
    _ = dataframe.def_method[PyDataFrame.labels](
        "labels", docstring="The row labels, as an index."
    )
    _ = dataframe.def_method[PyDataFrame.binary_frame](
        "binary_frame",
        docstring="An operation between two frames, aligning on both axes.",
    )
    _ = dataframe.def_method[PyDataFrame.binary_series](
        "binary_series",
        docstring="An operation between a frame and a series, along one axis.",
    )
    _ = dataframe.def_method[PyDataFrame.binary_value](
        "binary_value",
        docstring=(
            "An operation between every cell of a frame and one constant."
        ),
    )
    _ = dataframe.def_method[PyDataFrame.compare_frame](
        "compare_frame",
        docstring=(
            "A comparison between two frames labelled the same on both axes."
        ),
    )
    _ = dataframe.def_method[PyDataFrame.unary](
        "unary",
        docstring="One of the four unary operations, over every column.",
    )
    _ = dataframe.def_method[PyDataFrame.arrow_c_schema](
        "arrow_c_schema", docstring="The frame's Arrow schema, in a capsule."
    )
    _ = dataframe.def_method[PyDataFrame.arrow_c_array](
        "arrow_c_array",
        docstring="The frame's Arrow schema and data, in two capsules.",
    )
    _ = dataframe.def_method[PyDataFrame.arrow_c_stream](
        "arrow_c_stream",
        docstring="The frame as an Arrow stream, in a capsule.",
    )

    ref series = module.add_type[PySeries]("Series")
    _ = series.def_py_init[PySeries.py_init]()
    _ = series.def_method[PySeries.length](
        "length", docstring="The number of rows."
    )
    _ = series.def_method[PySeries.label](
        "label", docstring="The name of the column."
    )
    _ = series.def_method[PySeries.dtype](
        "dtype", docstring="The type, as firepanda spells it."
    )
    _ = series.def_method[PySeries.null_count](
        "null_count", docstring="How many rows are missing."
    )
    _ = series.def_method[PySeries.head]("head", docstring="The first n rows.")
    _ = series.def_method[PySeries.tail]("tail", docstring="The last n rows.")
    _ = series.def_method[PySeries.to_list](
        "to_list", docstring="Every value, copied into a Python list."
    )
    _ = series.def_method[PySeries.labels](
        "labels", docstring="The row labels, as an index."
    )
    _ = series.def_method[PySeries.binary_series](
        "binary_series",
        docstring="An operation between two series, matching rows by label.",
    )
    _ = series.def_method[PySeries.binary_value](
        "binary_value",
        docstring=(
            "An operation between every row of a series and one constant."
        ),
    )
    _ = series.def_method[PySeries.compare_series](
        "compare_series",
        docstring="A comparison between two series labelled the same.",
    )
    _ = series.def_method[PySeries.unary](
        "unary", docstring="One of the four unary operations, over every row."
    )
    _ = series.def_method[PySeries.arrow_c_schema](
        "arrow_c_schema", docstring="The column's Arrow schema, in a capsule."
    )
    _ = series.def_method[PySeries.arrow_c_array](
        "arrow_c_array",
        docstring="The column's Arrow schema and data, in two capsules.",
    )

    ref index = module.add_type[PyIndex]("Index")
    _ = index.def_py_init[PyIndex.py_init]()
    _ = index.def_method[PyIndex.length](
        "length", docstring="The number of labels."
    )
    _ = index.def_method[PyIndex.label](
        "label", docstring="The level name, or None."
    )
    _ = index.def_method[PyIndex.dtype](
        "dtype", docstring="The type of the labels, as firepanda spells it."
    )
    _ = index.def_method[PyIndex.inferred_type](
        "inferred_type", docstring="What pandas calls the kind of the labels."
    )
    _ = index.def_method[PyIndex.is_range](
        "is_range",
        docstring="Whether the labels are still an arithmetic range.",
    )
    _ = index.def_method[PyIndex.start](
        "start", docstring="The first label of a range."
    )
    _ = index.def_method[PyIndex.nbytes](
        "nbytes", docstring="The bytes the labels occupy."
    )
    _ = index.def_method[PyIndex.null_count](
        "null_count", docstring="How many labels are missing."
    )
    _ = index.def_method[PyIndex.at](
        "at", docstring="One label, as a Python value."
    )
    _ = index.def_method[PyIndex.to_list](
        "to_list", docstring="Every label, copied into a Python list."
    )
    _ = index.def_method[PyIndex.slice_rows](
        "slice_rows", docstring="A half open range of rows."
    )
    _ = index.def_method[PyIndex.take](
        "take", docstring="Labels gathered by position."
    )
    _ = index.def_method[PyIndex.is_unique](
        "is_unique", docstring="Whether every label appears once."
    )
    _ = index.def_method[PyIndex.is_monotonic_increasing](
        "is_monotonic_increasing",
        docstring="Whether the labels never decrease.",
    )
    _ = index.def_method[PyIndex.is_monotonic_decreasing](
        "is_monotonic_decreasing",
        docstring="Whether the labels never increase.",
    )
    _ = index.def_method[PyIndex.get_loc](
        "get_loc", docstring="Every position one label sits at."
    )
    _ = index.def_method[PyIndex.get_indexer](
        "get_indexer",
        docstring=(
            "Where each of a set of labels sits, with -1 for the missing."
        ),
    )
    _ = index.def_method[PyIndex.contains](
        "contains", docstring="Whether a label is in the index."
    )
    _ = index.def_method[PyIndex.equals](
        "equals", docstring="Whether two indexes hold the same labels."
    )
    _ = index.def_method[PyIndex.identical](
        "identical", docstring="Whether the labels and the name both match."
    )
    _ = index.def_method[PyIndex.same_as](
        "same_as",
        docstring="Whether two indexes are the same object underneath.",
    )
    _ = index.def_method[PyIndex.unique](
        "unique", docstring="The first of each label."
    )
    _ = index.def_method[PyIndex.renamed](
        "renamed", docstring="The index under a different level name."
    )
    _ = index.def_method[PyIndex.union](
        "union", docstring="Every label either side has."
    )
    _ = index.def_method[PyIndex.intersection](
        "intersection", docstring="Every label both sides have."
    )
    _ = index.def_method[PyIndex.difference](
        "difference",
        docstring="Every label this index has and the other does not.",
    )
    _ = index.def_method[PyIndex.symmetric_difference](
        "symmetric_difference", docstring="Every label exactly one side has."
    )
    _ = index.def_method[PyIndex.append](
        "append", docstring="One or several indexes put on the end of this one."
    )
    _ = index.def_method[PyIndex.delete](
        "delete",
        docstring="The index without the labels at a set of positions.",
    )
    _ = index.def_method[PyIndex.insert](
        "insert", docstring="The index with one label put in at a position."
    )
    _ = index.def_method[PyIndex.drop](
        "drop",
        docstring=(
            "The index without every row carrying one of a set of labels."
        ),
    )
    _ = index.def_method[PyIndex.putmask](
        "putmask",
        docstring="The index with the labels a mask picks out replaced.",
    )
    _ = index.def_method[PyIndex.get_slice_bound](
        "get_slice_bound",
        docstring="Where a label sits when the index is read in order.",
    )
    _ = index.def_method[PyIndex.slice_locs](
        "slice_locs",
        docstring="The half open row range a pair of labels describes.",
    )
    _ = index.def_method[PyIndex.slice_indexer](
        "slice_indexer",
        docstring="The same range with the step carried through.",
    )
    _ = index.def_method[PyIndex.arrow_c_schema](
        "arrow_c_schema", docstring="The labels' Arrow schema, in a capsule."
    )
    _ = index.def_method[PyIndex.arrow_c_array](
        "arrow_c_array",
        docstring="The labels' Arrow schema and data, in two capsules.",
    )
