# Generated by tools/bindings.py. Do not edit.
#
# Run `python tools/bindings.py` after changing the table in that file.
# CI runs it with --check and fails if this file is out of date.

"""The registration calls, one per binding.

This is the flat sequence document 13 section 7 explains cannot be
a loop.
"""

from std.python import PythonObject
from std.python.bindings import PythonModuleBuilder

from firepanda.py.frame import PyDataFrame, open_csv


def register(mut module: PythonModuleBuilder) raises:
    """Registers every binding on the module.

    Args:
        module: The builder to register on.
    """
    module.def_function[open_csv](
        "read_csv", docstring="Reads a CSV file into a frame."
    )

    ref dataframe = module.add_type[PyDataFrame]("DataFrame")
    _ = dataframe.def_py_init[PyDataFrame.py_init]()
    _ = dataframe.def_method[PyDataFrame.length](
        "length", docstring="The number of rows."
    )
    _ = dataframe.def_method[PyDataFrame.width](
        "width", docstring="The number of columns."
    )
    _ = dataframe.def_method[PyDataFrame.names](
        "names", docstring="The column names, in order."
    )
    _ = dataframe.def_method[PyDataFrame.head](
        "head", docstring="The first n rows."
    )
    _ = dataframe.def_method[PyDataFrame.tail](
        "tail", docstring="The last n rows."
    )
